/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * [Experimental] External data is data that is not contained in the Truss folder.
 *
 * Typically, this will be data stored remotely. This data is guaranteed to be made
 * available under the data directory of the truss.
 */
export type ExternalData = ExternalDataItem[];
/**
 * This enum will express all the types of registry
 * authentication we support.
 */
export type DockerAuthType =
  | "GCP_SERVICE_ACCOUNT_JSON"
  | "AWS_IAM"
  | "AWS_OIDC"
  | "GCP_OIDC"
  | "REGISTRY_SECRET";
/**
 * To determine the image builder path for trusses built from alternative server backends.
 * This enum is also used to gate development deployments to BasetenRemote
 * https://github.com/basetenlabs/truss/blob/7505c17a2ddd4a6fa626b9126772999dc8f3fa86/truss/remote/baseten/remote.py#L56-L57
 */
export type ModelServer = "TrussServer" | "TRT_LLM";
/**
 * syned with `pub enum ResolutionType` in truss-transfer
 */
export type ModelRepoSourceKind = "hf" | "gcs" | "s3" | "azure";
/**
 * Deprecated. Use 'weights' instead. Bundle model weights into your image at build time.
 */
export type ModelCache = ModelRepo[];
/**
 * Authentication method for downloading weights from the source.
 */
export type WeightsAuthMethod = "CUSTOM_SECRET" | "AWS_OIDC" | "GCP_OIDC";
/**
 * Configure Baseten Delivery Network (BDN) for model weight delivery with multi-tier caching.
 */
export type Weights = WeightsSource[];
export type TRTLLMConfiguration = TRTLLMConfigurationV1 | TRTLLMConfigurationV2;
export type ModelTRTLLMModel =
  | "encoder"
  | "encoder_bert"
  | "decoder"
  | "palmyra"
  | "qwen"
  | "llama"
  | "mistral"
  | "deepseek"
  | "whisper";
export type CheckpointSource =
  | "HF"
  | "GCS"
  | "S3"
  | "AZURE"
  | "LOCAL"
  | "REMOTE_URL"
  | "BASETEN_TRAINING";
export type ModelTRTLLMQuantizationType =
  | "no_quant"
  | "weights_int8"
  | "weights_kv_int8"
  | "weights_int4"
  | "weights_int4_kv_int8"
  | "smooth_quant"
  | "fp8"
  | "fp8_kv"
  | "fp4"
  | "fp4_kv"
  | "fp4_mlp_only";
export type ModelSpecDecMode = "DRAFT_TOKENS_EXTERNAL" | "LOOKAHEAD_DECODING";
export type ModelTRTLLMBatchSchedulerPolicy = "max_utilization" | "guaranteed_no_evict";
/**
 * syned with `pub enum ResolutionType` in truss-transfer
 */
export type ModelRepoSourceKind1 = "hf" | "gcs" | "s3" | "azure";
export type CacheInternal = ModelRepoCacheInternal[];

/**
 * Configuration for a Truss model deployment.
 */
export interface ModelConfig {
  /**
   * The name of your model. This is displayed in the model details page in the Baseten UI.
   */
  model_name?: string | null;
  /**
   * A flexible field for additional metadata. The entire config file is available to your model at runtime.
   */
  model_metadata?: {
    /**
     * Sample input that populates the Baseten playground.
     */
    example_model_input?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * A description of your model.
   */
  description?: string | null;
  /**
   * Path to a file containing example model inputs.
   */
  examples_filename?: string;
  /**
   * The folder for data files in your Truss.
   */
  data_dir?: string;
  /**
   * External data to be downloaded and made available under the data directory at serving time.
   */
  external_data?: ExternalData | null;
  /**
   * Use external_package_dirs to access custom packages located outside your Truss. This lets multiple Trusses share the same package.
   */
  external_package_dirs?: string[];
  /**
   * The Python version to use.
   */
  python_version?: string;
  /**
   * Use a custom Docker base image instead of the default Truss image.
   */
  base_image?: BaseImage | null;
  /**
   * Path to a dependency file. Supports requirements.txt, pyproject.toml, and uv.lock. Mutually exclusive with 'requirements'.
   */
  requirements_file?: string | null;
  /**
   * A list of Python dependencies in pip requirements file format. Mutually exclusive with 'requirements_file'.
   */
  requirements?: string[];
  /**
   * System packages that you would typically install using apt on a Debian operating system.
   */
  system_packages?: string[];
  /**
   * Key-value pairs exposed to the environment that the model executes in. Do not store secret values here.
   */
  environment_variables?: {
    [k: string]: string;
  };
  /**
   * Declare secrets your model needs at runtime, such as API keys or access tokens. Use null as a placeholder; store actual values in your organization settings.
   */
  secrets?: {
    [k: string]: string | null;
  };
  resources?: Resources;
  runtime?: Runtime;
  build?: Build;
  /**
   * A list of shell commands to run during Docker build. These commands execute after system packages and Python requirements are installed.
   */
  build_commands?: string[];
  /**
   * Deploy a custom Docker image that has its own HTTP server, without writing a Model class.
   */
  docker_server?: DockerServer | null;
  model_cache?: ModelCache;
  weights?: Weights;
  /**
   * TensorRT-LLM configuration for optimized LLM inference.
   */
  trt_llm?: TRTLLMConfiguration | null;
  /**
   * Configuration for deploying from training checkpoints.
   */
  training_checkpoints?: CheckpointList | null;
  /**
   * Configuration options for BIS LLM deployments. This field may change in the future.
   */
  bis_llm?: BISLLM | null;
  input_type?: string;
  model_framework?: string;
  model_type?: string;
  /**
   * The folder containing your model class.
   */
  model_module_dir?: string;
  model_class_filename?: string;
  /**
   * The name of the class that defines your Truss model. This class must implement at least a predict method.
   */
  model_class_name?: string;
  /**
   * The folder for custom packages in your Truss.
   */
  bundled_packages_dir?: string;
  use_local_src?: boolean;
  cache_internal?: CacheInternal;
  /**
   * If true, changes to your model code are automatically reloaded without restarting the server.
   */
  live_reload?: boolean;
  /**
   * Whether to apply library patches for improved compatibility.
   */
  apply_library_patches?: boolean;
  spec_version?: string;
  [k: string]: unknown;
}
/**
 * A piece of remote data, to be made available to the Truss at serving time.
 *
 * Remote data is downloaded and stored under Truss's data directory. Care should be taken
 * to avoid conflicts. This will get precedence if there's overlap.
 */
export interface ExternalDataItem {
  /**
   * URL to download the data from. Currently only files are allowed.
   */
  url: string;
  /**
   * Path relative to the data directory where the remote file will be downloaded.
   */
  local_data_path: string;
  /**
   * Download backend to use. Defaults to 'http_public'.
   */
  backend?: string;
  /**
   * Optional name for the download. Path relative to data directory.
   */
  name?: string | null;
  [k: string]: unknown;
}
/**
 * Use base_image to deploy a custom Docker image.
 */
export interface BaseImage {
  /**
   * The path to the Docker image.
   */
  image?: string;
  /**
   * A path to the Python executable on the image.
   */
  python_executable_path?: string;
  /**
   * Authentication configuration for a private Docker registry.
   */
  docker_auth?: DockerAuthSettings | null;
  [k: string]: unknown;
}
/**
 * Provides information about how to authenticate to the docker registry containing
 * the custom base image.
 */
export interface DockerAuthSettings {
  /**
   * AWS IAM role ARN for OIDC authentication.
   */
  aws_oidc_role_arn?: string | null;
  /**
   * AWS region for OIDC authentication.
   */
  aws_oidc_region?: string | null;
  /**
   * GCP service account name for OIDC authentication.
   */
  gcp_oidc_service_account?: string | null;
  /**
   * GCP workload identity provider for OIDC authentication.
   */
  gcp_oidc_workload_id_provider?: string | null;
  auth_method: DockerAuthType;
  registry?: string | null;
  secret_name?: string | null;
  aws_access_key_id_secret_name?: string;
  aws_secret_access_key_secret_name?: string;
  [k: string]: unknown;
}
/**
 * Compute resources that your model needs, including CPU, memory, and GPU resources.
 */
export interface Resources {
  /**
   * CPU resources needed, expressed as either a raw number or millicpus. For example, 500m is half of a CPU core.
   */
  cpu?: string;
  /**
   * CPU RAM needed, expressed as a number with units. Units include Gi (Gibibytes), G (Gigabytes), Mi (Mebibytes), and M (Megabytes).
   */
  memory?: string;
  /**
   * The GPU type for your instance. To request multiple GPUs, use the ':' operator (e.g. L4:4).
   */
  accelerator?: string | null;
  /**
   * The full SKU name for the instance type. When specified, cpu, memory, and accelerator fields are ignored.
   */
  instance_type?: string | null;
  /**
   * Number of nodes for multi-node deployments.
   */
  node_count?: number | null;
  [k: string]: unknown;
}
/**
 * Runtime settings for your model instance.
 */
export interface Runtime {
  /**
   * The number of concurrent requests that can run in your model's predict method. Increase this if your model supports parallelism.
   */
  predict_concurrency?: number;
  /**
   * The timeout in seconds for streaming read operations.
   */
  streaming_read_timeout?: number;
  /**
   * If true, enables trace data export with built-in OTEL instrumentation. May add performance overhead.
   */
  enable_tracing_data?: boolean;
  /**
   * If true, sets the Truss server log level to DEBUG instead of INFO.
   */
  enable_debug_logs?: boolean;
  /**
   * The transport protocol for your model. Supports http (default), websocket, and grpc.
   */
  transport?: HTTPOptions | WebsocketOptions | GRPCOptions;
  /**
   * DEPRECATED. Do not set manually. Automatically inferred from transport.kind == websocket.
   */
  is_websocket_endpoint?: boolean | null;
  health_checks?: HealthChecks;
  oidc?: OIDC;
  remote_ssh?: RemoteSSH;
  /**
   * Egress network restrictions for the model version. When unset, all egress is allowed (default).
   */
  egress_restrictions?: EgressRestrictions | null;
  /**
   * By default, truss servers are built from the same release as the CLI used to push. This field allows specifying a pinned/specific version instead.
   */
  truss_server_version_override?: string | null;
  [k: string]: unknown;
}
export interface HTTPOptions {
  kind?: "http";
}
export interface WebsocketOptions {
  kind?: "websocket";
  ping_interval_seconds?: number | null;
  ping_timeout_seconds?: number | null;
}
export interface GRPCOptions {
  kind?: "grpc";
}
/**
 * Custom health check configuration for your deployments.
 */
export interface HealthChecks {
  /**
   * The delay in seconds before starting restart checks. Defaults to platform-determined value when not set.
   */
  restart_check_delay_seconds?: number | null;
  /**
   * The time in seconds after which an unhealthy instance is restarted. Defaults to platform-determined value when not set.
   */
  restart_threshold_seconds?: number | null;
  /**
   * The time in seconds after which traffic is stopped to an unhealthy instance. Defaults to platform-determined value when not set.
   */
  stop_traffic_threshold_seconds?: number | null;
  /**
   * The time in seconds to wait for a model to start before marking it as unhealthy. Defaults to platform-determined value when not set.
   */
  startup_threshold_seconds?: number | null;
  [k: string]: unknown;
}
/**
 * Configuration for runtime-mounting of an OIDC bearer token.
 */
export interface OIDC {
  /**
   * If true, mounts an OIDC bearer token for your model to access at runtime.
   */
  enabled?: boolean | null;
  [k: string]: unknown;
}
/**
 * Configuration for SSH access to running model instances.
 */
export interface RemoteSSH {
  /**
   * If true, enables SSH access to running model instances.
   */
  enabled?: boolean;
  [k: string]: unknown;
}
/**
 * Egress network restrictions for a model version.
 *
 * Setting both ``ip_allow_list`` and ``fqdn_allow_list`` to ``null`` or
 * ``[]`` blocks all outbound network egress. Omitting the
 * ``egress_restrictions`` block (or setting it to ``null``) preserves the
 * default behavior of allowing all egress.
 */
export interface EgressRestrictions {
  /**
   * Allowed outbound IPv4 addresses or CIDR ranges. Use null or [] alongside an equally restrictive fqdn_allow_list to block all egress.
   */
  ip_allow_list?: string[] | null;
  /**
   * Allowed outbound fully-qualified domain names. Supports wildcards: '*' may appear anywhere in a label.
   */
  fqdn_allow_list?: string[] | null;
  [k: string]: unknown;
}
/**
 * Build-time configuration, including secret access during Docker builds.
 */
export interface Build {
  model_server?: ModelServer;
  arguments?: {
    [k: string]: unknown;
  };
  /**
   * Grants access to secrets during the build. Provide a mapping between a secret and a path on the image.
   */
  secret_to_path_mapping?: {
    [k: string]: string;
  };
  no_cache?: boolean;
  [k: string]: unknown;
}
/**
 * Deploy a custom Docker image that has its own HTTP server, without writing a Model class.
 */
export interface DockerServer {
  /**
   * The command to start the server. Required when no_build is not true.
   */
  start_command?: string | null;
  /**
   * The port where the server runs. Port 8080 is reserved by Baseten's internal reverse proxy and cannot be used.
   */
  server_port: number;
  /**
   * The endpoint for inference requests. This is mapped to Baseten's /predict route.
   */
  predict_endpoint: string;
  /**
   * The endpoint for readiness probes. Determines when the container can accept traffic.
   */
  readiness_endpoint: string;
  /**
   * The endpoint for liveness probes. Determines if the container needs to be restarted.
   */
  liveness_endpoint: string;
  /**
   * The Linux UID to run the server process as inside the container. Use this when your base image expects a specific non-root user (for example, NVIDIA NIM containers).
   */
  run_as_user_id?: number | null;
  /**
   * Skip the build step and deploy the base image as-is. Baseten copies the image to its container registry without running docker build or modifying the image in any way.
   */
  no_build?: boolean | null;
  [k: string]: unknown;
}
export interface ModelRepo {
  repo_id: string;
  revision?: string;
  allow_patterns?: string[] | null;
  ignore_patterns?: string[] | null;
  volume_folder?: string | null;
  use_volume: boolean;
  kind?: ModelRepoSourceKind;
  runtime_secret_name?: string;
  [k: string]: unknown;
}
/**
 * Configuration for a weights source in the new weights API.
 *
 * Uses a URI-based `source` field with a required scheme prefix:
 * - hf:// -> HuggingFace (e.g., "hf://meta-llama/Llama-2-7b" or "hf://meta-llama/Llama-2-7b@main")
 * - s3:// -> AWS S3 (e.g., "s3://bucket/path")
 * - gs:// -> Google Cloud Storage (e.g., "gs://bucket/path")
 * - azure:// -> Azure Blob Storage (e.g., "azure://account/container/path")
 * - r2:// -> CloudFlare R2 Storage (e.g., "r2://account_id.bucket/path")
 * - cw:// -> CoreWeave AI Object Storage (e.g., "cw://bucket/path")
 * - https:// -> Direct URL download (e.g., "https://example.com/model.bin")
 *
 * For HuggingFace sources, you can specify a revision (branch, tag, or commit SHA)
 * using the @{rev} suffix: "hf://owner/repo@revision"
 *
 * Authentication can be specified either:
 * - Using the `auth` section (required for OIDC):
 *     auth:
 *       auth_method: AWS_OIDC
 *       aws_oidc_role_arn: <role_arn>
 *       aws_oidc_region: <region>
 * - Using `auth_secret_name` at the top level (or in the `auth` section)
 */
export interface WeightsSource {
  /**
   * URI with scheme prefix. Use hf://, s3://, gs://, azure://, r2://, cw://, or https://. For HuggingFace, use @revision suffix (e.g., hf://owner/repo@main).
   */
  source: string;
  /**
   * Absolute path where weights will be mounted at runtime.
   */
  mount_location: string;
  /**
   * Authentication configuration for accessing the weights source.
   */
  auth?: WeightsAuth | null;
  /**
   * Baseten secret name containing credentials. Can also be specified in auth.auth_secret_name.
   */
  auth_secret_name?: string | null;
  /**
   * File patterns to include (e.g., ['*.safetensors']).
   */
  allow_patterns?: string[] | null;
  /**
   * File patterns to exclude (e.g., ['*.md']).
   */
  ignore_patterns?: string[] | null;
  [k: string]: unknown;
}
/**
 * Authentication configuration for a weights source.
 *
 * This can be used to specify OIDC-based authentication for cloud storage sources,
 * or a Baseten secret name for access key authentication.
 */
export interface WeightsAuth {
  /**
   * AWS IAM role ARN for OIDC authentication.
   */
  aws_oidc_role_arn?: string | null;
  /**
   * AWS region for OIDC authentication.
   */
  aws_oidc_region?: string | null;
  /**
   * GCP service account name for OIDC authentication.
   */
  gcp_oidc_service_account?: string | null;
  /**
   * GCP workload identity provider for OIDC authentication.
   */
  gcp_oidc_workload_id_provider?: string | null;
  auth_method: WeightsAuthMethod;
  /**
   * Baseten secret name containing credentials for accessing the source.
   */
  auth_secret_name?: string | null;
  [k: string]: unknown;
}
export interface TRTLLMConfigurationV1 {
  build: ModelTRTLLMBuildConfiguration;
  inference_stack?: "v1";
  runtime?: ModelTRTLLMRuntimeConfiguration1;
  version_overrides?: VersionsOverrides;
  [k: string]: unknown;
}
export interface ModelTRTLLMBuildConfiguration {
  base_model?: ModelTRTLLMModel;
  max_seq_len?: number | null;
  max_batch_size?: number;
  max_num_tokens?: number;
  max_beam_width?: number;
  max_prompt_embedding_table_size?: number;
  checkpoint_repository?: CheckpointRepository | null;
  gather_all_token_logits?: boolean;
  strongly_typed?: boolean;
  quantization_type?: ModelTRTLLMQuantizationType;
  quantization_config?: ModelTRTQuantizationConfiguration;
  tensor_parallel_count?: number;
  pipeline_parallel_count?: number;
  moe_expert_parallel_option?: number;
  sequence_parallel_count?: number;
  plugin_configuration?: ModelTRTLLMPluginConfiguration;
  num_builder_gpus?: number | null;
  speculator?: ModelSpeculatorConfiguration | null;
  lora_adapters?: {
    [k: string]: CheckpointRepository;
  } | null;
  lora_configuration?: ModelTRTLLMLoraConfiguration | null;
  skip_build_result?: boolean;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-zA-Z0-9_\-\.:]+$".
 */
export interface CheckpointRepository {
  source: CheckpointSource;
  repo: string;
  revision?: string | null;
  runtime_secret_name?: string;
  [k: string]: unknown;
}
/**
 * Configuration for quantization of TRT models
 *
 * Args:
 *     calib_size (int, optional): Size of calibration dataset. Defaults to 1024.
 *         recommended to increase for production runs (e.g. 1536), or decrease e.g. to 256 for quick testing.
 *     calib_dataset (str, optional): Hugginface dataset to use for calibration. Defaults to 'cnn_dailymail'.
 *         uses split='train' and  quantized based on 'text' column.
 *     calib_max_seq_length (int, optional): Maximum sequence length for calibration. Defaults to 2048.
 */
export interface ModelTRTQuantizationConfiguration {
  calib_size?: number;
  calib_dataset?: string;
  calib_max_seq_length?: number;
  [k: string]: unknown;
}
export interface ModelTRTLLMPluginConfiguration {
  paged_kv_cache?: boolean;
  use_paged_context_fmha?: boolean;
  use_fp8_context_fmha?: boolean;
  [k: string]: unknown;
}
export interface ModelSpeculatorConfiguration {
  speculative_decoding_mode?: ModelSpecDecMode;
  num_draft_tokens?: number | null;
  checkpoint_repository?: CheckpointRepository | null;
  runtime?: ModelTRTLLMRuntimeConfiguration;
  build?: ModelTRTLLMBuildConfiguration | null;
  lookahead_windows_size?: number | null;
  lookahead_ngram_size?: number | null;
  lookahead_verification_set_size?: number | null;
  enable_b10_lookahead?: boolean | null;
  [k: string]: unknown;
}
export interface ModelTRTLLMRuntimeConfiguration {
  kv_cache_free_gpu_mem_fraction?: number;
  kv_cache_host_memory_bytes?: number | null;
  enable_chunked_context?: boolean;
  batch_scheduler_policy?: ModelTRTLLMBatchSchedulerPolicy;
  request_default_max_tokens?: number | null;
  served_model_name?: string | null;
  total_token_limit?: number;
  webserver_default_route?: ("/v1/embeddings" | "/rerank" | "/predict" | "/predict_tokens") | null;
  [k: string]: unknown;
}
export interface ModelTRTLLMLoraConfiguration {
  max_lora_rank?: number;
  lora_target_modules?: string[];
  [k: string]: unknown;
}
export interface ModelTRTLLMRuntimeConfiguration1 {
  kv_cache_free_gpu_mem_fraction?: number;
  kv_cache_host_memory_bytes?: number | null;
  enable_chunked_context?: boolean;
  batch_scheduler_policy?: ModelTRTLLMBatchSchedulerPolicy;
  request_default_max_tokens?: number | null;
  served_model_name?: string | null;
  total_token_limit?: number;
  webserver_default_route?: ("/v1/embeddings" | "/rerank" | "/predict" | "/predict_tokens") | null;
  [k: string]: unknown;
}
export interface VersionsOverrides {
  engine_builder_version?: string | null;
  briton_version?: string | null;
  bei_version?: string | null;
  bei_bert_version?: string | null;
  v2_llm_version?: string | null;
  [k: string]: unknown;
}
export interface TRTLLMConfigurationV2 {
  inference_stack?: "v2";
  build: ModelTRTLLMBuildConfiguration;
  runtime: TRTLLMRuntimeConfigurationV2;
  version_overrides?: VersionsOverrides1;
  [k: string]: unknown;
}
export interface TRTLLMRuntimeConfigurationV2 {
  max_seq_len?: number | null;
  max_batch_size?: number;
  max_num_tokens?: number;
  tensor_parallel_size?: number;
  enable_chunked_prefill?: boolean;
  served_model_name?: string | null;
  patch_kwargs?: {
    [k: string]:
      | string
      | number
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | null;
  };
  [k: string]: unknown;
}
export interface VersionsOverrides1 {
  engine_builder_version?: string | null;
  briton_version?: string | null;
  bei_version?: string | null;
  bei_bert_version?: string | null;
  v2_llm_version?: string | null;
  [k: string]: unknown;
}
export interface CheckpointList {
  /**
   * The folder to download the checkpoints to.
   */
  download_folder?: string;
  artifact_references?: TrainingArtifactReference[];
  /**
   * Loops checkpoint IDs to deploy. Mutually exclusive with artifact_references.
   */
  loops_checkpoint_ids?: string[];
  [k: string]: unknown;
}
export interface TrainingArtifactReference {
  /**
   * The training job id that the artifact reference belongs to.
   */
  training_job_id: string;
  /**
   * The paths of the files to download which can contain * or ?.
   */
  paths?: string[];
  [k: string]: unknown;
}
/**
 * Configuration options for BIS LLM deployments.
 */
export interface BISLLM {
  /**
   * Configuration options for BIS LLM deployments.
   */
  config?: {
    [k: string]: unknown;
  } | null;
  /**
   * The version of the BIS LLM deployment stack.
   */
  version?: string;
  /**
   * Additional autoscaling configuration
   */
  additional_autoscaling_config?: AdditionalAutoscalingConfig | null;
  [k: string]: unknown;
}
/**
 * Additional autoscaling configuration for in-flight token metrics.
 */
export interface AdditionalAutoscalingConfig {
  /**
   * List of metric targets for autoscaling.
   */
  metrics: AutoscalingMetric[];
}
export interface AutoscalingMetric {
  name: string;
  target: number;
}
export interface ModelRepoCacheInternal {
  repo_id: string;
  revision?: string;
  allow_patterns?: string[] | null;
  ignore_patterns?: string[] | null;
  volume_folder?: string | null;
  use_volume?: boolean;
  kind?: ModelRepoSourceKind1;
  runtime_secret_name?: string;
  [k: string]: unknown;
}
