// Code generated by apigen/clientgen. DO NOT EDIT.

import type {
  ApplyEditRequest,
  ApplyEditResponse,
  ContentSearchResponse,
  DeleteFilesystemQuery,
  DeleteFilesystemTreeQuery,
  DeleteNetworkProcessMonitorResponse,
  DriveListResponse,
  DriveMountRequest,
  DriveMountResponse,
  DriveUnmountResponse,
  ErrorResponse,
  ExportOptions,
  ExportProgress,
  ExportResult,
  FileRequest,
  FindResponse,
  FuzzySearchResponse,
  GetCodegenRerankingQuery,
  GetFilesystemContentSearchQuery,
  GetFilesystemFindQuery,
  GetFilesystemQuery,
  GetFilesystemResponse,
  GetFilesystemSearchQuery,
  GetFilesystemTreeResponse,
  GetNetworkProcessPortsResponse,
  GetProcessResponse,
  GetWatchFilesystemQuery,
  HandlerReloadResponse,
  HealthResponse,
  MultipartCompleteRequest,
  MultipartInitiateRequest,
  MultipartInitiateResponse,
  MultipartListPartsResponse,
  MultipartListUploadsResponse,
  MultipartUploadPartResponse,
  PortMonitorRequest,
  PostNetworkProcessMonitorResponse,
  ProcessLogs,
  ProcessRequest,
  ProcessResponse,
  PutFilesystemMultipartPartQuery,
  PutFilesystemTreeResponse,
  QuiesceStatus,
  RerankingResponse,
  SuccessResponse,
  TreeRequest,
  TunnelConfigRequest,
  UpgradeRequest,
} from "./models.gen";

export class ResponseError extends Error {
  constructor(
    public readonly statusCode: number,
    public readonly body: string,
  ) {
    super(`baseten API error (HTTP ${statusCode}): ${body}`);
  }
}

export class ResponseErrorResponse extends Error {
  public readonly error_response: ErrorResponse;
  constructor(statusCode: number, data: unknown) {
    super(`baseten API error (HTTP ${statusCode}): ${JSON.stringify(data)}`);
    this.error_response = data as ErrorResponse;
  }
}

const ERROR_TYPES: Record<string, new (statusCode: number, data: unknown) => Error> = {
  ErrorResponse: ResponseErrorResponse,
};

interface ApiRequest {
  method: string;
  pathFmt: string;
  pathArgs: string[];
  query: Record<string, unknown> | null;
  body: unknown;
  /** Request body encoding. Defaults to application/json. */
  bodyContentType?: string;
  /** Accept header to send. Omitted when the response is JSON. */
  accept?: string;
  /** Accepted success statuses. Defaults to [200]. */
  successCodes?: number[];
  errorCodes: Record<number, string> | null;
}

export class ApiClient {
  /**
   * Generated HTTP client for the Baseten API.
   *
   * Methods on this client are generated from the OpenAPI specification
   * and are NOT covered by any stability or compatibility guarantees.
   * They may change without notice between versions.
   */
  private readonly baseUrl: string;
  private readonly headers: Record<string, string>;
  private readonly fetchImpl: typeof fetch;

  constructor(options: { baseUrl: string; headers: Record<string, string>; fetch?: typeof fetch }) {
    this.baseUrl = options.baseUrl;
    this.headers = options.headers;
    this.fetchImpl = options.fetch ?? globalThis.fetch;
  }

  /** Detach a drive from a local path */
  async deleteDrivesMount(params: { mountPath: string }): Promise<DriveUnmountResponse> {
    return this._doJson<DriveUnmountResponse>({
      method: "DELETE",
      pathFmt: "/drives/mount/{}",
      pathArgs: [params.mountPath],
      query: null,
      body: null,
      errorCodes: { 400: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Delete file or directory */
  async deleteFilesystem(params: {
    path: string;
    query?: DeleteFilesystemQuery;
  }): Promise<SuccessResponse> {
    return this._doJson<SuccessResponse>({
      method: "DELETE",
      pathFmt: "/filesystem/{}",
      pathArgs: [params.path],
      query: params.query ?? null,
      body: null,
      errorCodes: { 404: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Abort multipart upload */
  async deleteFilesystemMultipartAbort(params: { uploadId: string }): Promise<SuccessResponse> {
    return this._doJson<SuccessResponse>({
      method: "DELETE",
      pathFmt: "/filesystem-multipart/{}/abort",
      pathArgs: [params.uploadId],
      query: null,
      body: null,
      errorCodes: { 400: "ErrorResponse", 404: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Delete directory tree */
  async deleteFilesystemTree(params: {
    path: string;
    query?: DeleteFilesystemTreeQuery;
  }): Promise<SuccessResponse> {
    return this._doJson<SuccessResponse>({
      method: "DELETE",
      pathFmt: "/filesystem/tree/{}",
      pathArgs: [params.path],
      query: params.query ?? null,
      body: null,
      errorCodes: { 400: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Stop monitoring ports for a process */
  async deleteNetworkProcessMonitor(params: {
    pid: string;
  }): Promise<DeleteNetworkProcessMonitorResponse> {
    return this._doJson<DeleteNetworkProcessMonitorResponse>({
      method: "DELETE",
      pathFmt: "/network/process/{}/monitor",
      pathArgs: [params.pid],
      query: null,
      body: null,
      errorCodes: { 400: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Disconnect tunnel */
  async deleteNetworkTunnel(): Promise<SuccessResponse> {
    return this._doJson<SuccessResponse>({
      method: "DELETE",
      pathFmt: "/network/tunnel",
      pathArgs: [],
      query: null,
      body: null,
      errorCodes: { 400: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Stop a process */
  async deleteProcess(params: { identifier: string }): Promise<SuccessResponse> {
    return this._doJson<SuccessResponse>({
      method: "DELETE",
      pathFmt: "/process/{}",
      pathArgs: [params.identifier],
      query: null,
      body: null,
      errorCodes: { 404: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Kill a process */
  async deleteProcessKill(params: { identifier: string }): Promise<SuccessResponse> {
    return this._doJson<SuccessResponse>({
      method: "DELETE",
      pathFmt: "/process/{}/kill",
      pathArgs: [params.identifier],
      query: null,
      body: null,
      errorCodes: { 404: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Close a process's stdin */
  async deleteProcessStdin(params: { identifier: string }): Promise<SuccessResponse> {
    return this._doJson<SuccessResponse>({
      method: "DELETE",
      pathFmt: "/process/{}/stdin",
      pathArgs: [params.identifier],
      query: null,
      body: null,
      errorCodes: { 404: "ErrorResponse", 409: "ErrorResponse" },
    });
  }

  /** Get the archive status */
  async getArchiveStatus(): Promise<QuiesceStatus> {
    return this._doJson<QuiesceStatus>({
      method: "GET",
      pathFmt: "/archive/status",
      pathArgs: [],
      query: null,
      body: null,
      errorCodes: null,
    });
  }

  /** Code reranking/semantic search */
  async getCodegenReranking(params: {
    path: string;
    query: GetCodegenRerankingQuery;
  }): Promise<RerankingResponse> {
    return this._doJson<RerankingResponse>({
      method: "GET",
      pathFmt: "/codegen/reranking/{}",
      pathArgs: [params.path],
      query: params.query ?? null,
      body: null,
      errorCodes: { 400: "ErrorResponse", 422: "ErrorResponse", 503: "ErrorResponse" },
    });
  }

  /** List currently mounted drives */
  async getDrivesMount(): Promise<DriveListResponse> {
    return this._doJson<DriveListResponse>({
      method: "GET",
      pathFmt: "/drives/mount",
      pathArgs: [],
      query: null,
      body: null,
      errorCodes: { 500: "ErrorResponse" },
    });
  }

  /** Get file or directory information */
  async getFilesystem(params: {
    path: string;
    query?: GetFilesystemQuery;
  }): Promise<GetFilesystemResponse> {
    return this._doJson<GetFilesystemResponse>({
      method: "GET",
      pathFmt: "/filesystem/{}",
      pathArgs: [params.path],
      query: params.query ?? null,
      body: null,
      errorCodes: { 404: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Get file or directory information. Returns the response unread, in the requested content type. */
  async getFilesystemRaw(params: {
    path: string;
    accept: "application/json" | "application/octet-stream";
    query?: GetFilesystemQuery;
  }): Promise<Response> {
    return this._do({
      method: "GET",
      pathFmt: "/filesystem/{}",
      pathArgs: [params.path],
      query: params.query ?? null,
      body: null,
      accept: params.accept,
      errorCodes: { 404: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Search for text content in files */
  async getFilesystemContentSearch(params: {
    path: string;
    query: GetFilesystemContentSearchQuery;
  }): Promise<ContentSearchResponse> {
    return this._doJson<ContentSearchResponse>({
      method: "GET",
      pathFmt: "/filesystem-content-search/{}",
      pathArgs: [params.path],
      query: params.query ?? null,
      body: null,
      errorCodes: { 400: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Find files and directories */
  async getFilesystemFind(params: {
    path: string;
    query?: GetFilesystemFindQuery;
  }): Promise<FindResponse> {
    return this._doJson<FindResponse>({
      method: "GET",
      pathFmt: "/filesystem-find/{}",
      pathArgs: [params.path],
      query: params.query ?? null,
      body: null,
      errorCodes: { 400: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** List multipart uploads */
  async getFilesystemMultipart(): Promise<MultipartListUploadsResponse> {
    return this._doJson<MultipartListUploadsResponse>({
      method: "GET",
      pathFmt: "/filesystem-multipart",
      pathArgs: [],
      query: null,
      body: null,
      errorCodes: { 500: "ErrorResponse" },
    });
  }

  /** List parts */
  async getFilesystemMultipartParts(params: {
    uploadId: string;
  }): Promise<MultipartListPartsResponse> {
    return this._doJson<MultipartListPartsResponse>({
      method: "GET",
      pathFmt: "/filesystem-multipart/{}/parts",
      pathArgs: [params.uploadId],
      query: null,
      body: null,
      errorCodes: { 400: "ErrorResponse", 404: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Fuzzy search for files and directories */
  async getFilesystemSearch(params: {
    path: string;
    query?: GetFilesystemSearchQuery;
  }): Promise<FuzzySearchResponse> {
    return this._doJson<FuzzySearchResponse>({
      method: "GET",
      pathFmt: "/filesystem-search/{}",
      pathArgs: [params.path],
      query: params.query ?? null,
      body: null,
      errorCodes: { 400: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Get directory tree */
  async getFilesystemTree(params: { path: string }): Promise<GetFilesystemTreeResponse> {
    return this._doJson<GetFilesystemTreeResponse>({
      method: "GET",
      pathFmt: "/filesystem/tree/{}",
      pathArgs: [params.path],
      query: null,
      body: null,
      errorCodes: { 400: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Health check */
  async getHealth(): Promise<HealthResponse> {
    return this._doJson<HealthResponse>({
      method: "GET",
      pathFmt: "/health",
      pathArgs: [],
      query: null,
      body: null,
      errorCodes: null,
    });
  }

  /** Get open ports for a process */
  async getNetworkProcessPorts(params: { pid: string }): Promise<GetNetworkProcessPortsResponse> {
    return this._doJson<GetNetworkProcessPortsResponse>({
      method: "GET",
      pathFmt: "/network/process/{}/ports",
      pathArgs: [params.pid],
      query: null,
      body: null,
      errorCodes: { 400: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** List all processes */
  async getProcess(): Promise<GetProcessResponse> {
    return this._doJson<GetProcessResponse>({
      method: "GET",
      pathFmt: "/process",
      pathArgs: [],
      query: null,
      body: null,
      errorCodes: null,
    });
  }

  /** Get process by identifier */
  async getProcessIdentifier(params: { identifier: string }): Promise<ProcessResponse> {
    return this._doJson<ProcessResponse>({
      method: "GET",
      pathFmt: "/process/{}",
      pathArgs: [params.identifier],
      query: null,
      body: null,
      errorCodes: { 404: "ErrorResponse" },
    });
  }

  /** Get process logs */
  async getProcessLogs(params: { identifier: string }): Promise<ProcessLogs> {
    return this._doJson<ProcessLogs>({
      method: "GET",
      pathFmt: "/process/{}/logs",
      pathArgs: [params.identifier],
      query: null,
      body: null,
      errorCodes: { 404: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Stream process logs in real time */
  async getProcessLogsStream(params: { identifier: string }): Promise<Response> {
    return this._do({
      method: "GET",
      pathFmt: "/process/{}/logs/stream",
      pathArgs: [params.identifier],
      query: null,
      body: null,
      accept: "text/plain",
      errorCodes: null,
    });
  }

  /** Stream file modification events in a directory */
  async getWatchFilesystem(params: {
    path: string;
    query?: GetWatchFilesystemQuery;
  }): Promise<Response> {
    return this._do({
      method: "GET",
      pathFmt: "/watch/filesystem/{}",
      pathArgs: [params.path],
      query: params.query ?? null,
      body: null,
      accept: "text/plain",
      errorCodes: null,
    });
  }

  /** Export the filesystem changes to a presigned URL */
  async postArchiveExport(params: {
    request: ExportOptions;
  }): Promise<{ status: 200; data: ExportResult } | { status: 202; data: ExportProgress }> {
    return (await this._doJsonWithStatus<ExportResult | ExportProgress>({
      method: "POST",
      pathFmt: "/archive/export",
      pathArgs: [],
      query: null,
      body: params.request,
      successCodes: [200, 202],
      errorCodes: { 400: "ErrorResponse", 409: "ErrorResponse", 500: "ErrorResponse" },
    })) as { status: 200; data: ExportResult } | { status: 202; data: ExportProgress };
  }

  /** Lift the archive freeze */
  async postArchiveResume(): Promise<QuiesceStatus> {
    return this._doJson<QuiesceStatus>({
      method: "POST",
      pathFmt: "/archive/resume",
      pathArgs: [],
      query: null,
      body: null,
      errorCodes: { 409: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Attach a drive to a local path */
  async postDrivesMount(params: { request: DriveMountRequest }): Promise<DriveMountResponse> {
    return this._doJson<DriveMountResponse>({
      method: "POST",
      pathFmt: "/drives/mount",
      pathArgs: [],
      query: null,
      body: params.request,
      errorCodes: {
        400: "ErrorResponse",
        403: "ErrorResponse",
        409: "ErrorResponse",
        500: "ErrorResponse",
      },
    });
  }

  /** Reload environment from guest metadata */
  async postEnvironmentReload(): Promise<HandlerReloadResponse> {
    return this._doJson<HandlerReloadResponse>({
      method: "POST",
      pathFmt: "/environment/reload",
      pathArgs: [],
      query: null,
      body: null,
      errorCodes: { 404: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Complete multipart upload */
  async postFilesystemMultipartComplete(params: {
    uploadId: string;
    request: MultipartCompleteRequest;
  }): Promise<SuccessResponse> {
    return this._doJson<SuccessResponse>({
      method: "POST",
      pathFmt: "/filesystem-multipart/{}/complete",
      pathArgs: [params.uploadId],
      query: null,
      body: params.request,
      errorCodes: { 400: "ErrorResponse", 404: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Initiate multipart upload */
  async postFilesystemMultipartInitiate(params: {
    path: string;
    request: MultipartInitiateRequest;
  }): Promise<MultipartInitiateResponse> {
    return this._doJson<MultipartInitiateResponse>({
      method: "POST",
      pathFmt: "/filesystem-multipart/initiate/{}",
      pathArgs: [params.path],
      query: null,
      body: params.request,
      errorCodes: { 400: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Start monitoring ports for a process */
  async postNetworkProcessMonitor(params: {
    pid: string;
    request: PortMonitorRequest;
  }): Promise<PostNetworkProcessMonitorResponse> {
    return this._doJson<PostNetworkProcessMonitorResponse>({
      method: "POST",
      pathFmt: "/network/process/{}/monitor",
      pathArgs: [params.pid],
      query: null,
      body: params.request,
      errorCodes: { 400: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Execute a command */
  async postProcess(params: { request: ProcessRequest }): Promise<ProcessResponse> {
    return this._doJson<ProcessResponse>({
      method: "POST",
      pathFmt: "/process",
      pathArgs: [],
      query: null,
      body: params.request,
      errorCodes: { 400: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Execute a command. Returns the response unread, in the requested content type. */
  async postProcessRaw(params: {
    accept: "application/json" | "text/event-stream";
    request: ProcessRequest;
  }): Promise<Response> {
    return this._do({
      method: "POST",
      pathFmt: "/process",
      pathArgs: [],
      query: null,
      body: params.request,
      accept: params.accept,
      errorCodes: { 400: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Write to a process's stdin */
  async postProcessStdin(params: {
    identifier: string;
    request: BodyInit;
  }): Promise<SuccessResponse> {
    return this._doJson<SuccessResponse>({
      method: "POST",
      pathFmt: "/process/{}/stdin",
      pathArgs: [params.identifier],
      query: null,
      body: params.request,
      bodyContentType: "application/octet-stream",
      errorCodes: {
        404: "ErrorResponse",
        409: "ErrorResponse",
        413: "ErrorResponse",
        500: "ErrorResponse",
        503: "ErrorResponse",
      },
    });
  }

  /** Upgrade the sandbox-api */
  async postUpgrade(params: { request: UpgradeRequest }): Promise<SuccessResponse> {
    return this._doJson<SuccessResponse>({
      method: "POST",
      pathFmt: "/upgrade",
      pathArgs: [],
      query: null,
      body: params.request,
      errorCodes: { 500: "ErrorResponse" },
    });
  }

  /** Apply code edit */
  async putCodegenFastapply(params: {
    path: string;
    request: ApplyEditRequest;
  }): Promise<ApplyEditResponse> {
    return this._doJson<ApplyEditResponse>({
      method: "PUT",
      pathFmt: "/codegen/fastapply/{}",
      pathArgs: [params.path],
      query: null,
      body: params.request,
      errorCodes: { 400: "ErrorResponse", 422: "ErrorResponse", 503: "ErrorResponse" },
    });
  }

  /** Create or update a file or directory */
  async putFilesystem(params: { path: string; request: FileRequest }): Promise<SuccessResponse> {
    return this._doJson<SuccessResponse>({
      method: "PUT",
      pathFmt: "/filesystem/{}",
      pathArgs: [params.path],
      query: null,
      body: params.request,
      errorCodes: { 400: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Upload part */
  async putFilesystemMultipartPart(params: {
    uploadId: string;
    query: PutFilesystemMultipartPartQuery;
    request: FormData;
  }): Promise<MultipartUploadPartResponse> {
    return this._doJson<MultipartUploadPartResponse>({
      method: "PUT",
      pathFmt: "/filesystem-multipart/{}/part",
      pathArgs: [params.uploadId],
      query: params.query ?? null,
      body: params.request,
      bodyContentType: "multipart/form-data",
      errorCodes: { 400: "ErrorResponse", 404: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Create or update directory tree */
  async putFilesystemTree(params: {
    path: string;
    request: TreeRequest;
  }): Promise<PutFilesystemTreeResponse> {
    return this._doJson<PutFilesystemTreeResponse>({
      method: "PUT",
      pathFmt: "/filesystem/tree/{}",
      pathArgs: [params.path],
      query: null,
      body: params.request,
      errorCodes: { 400: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  /** Update tunnel configuration */
  async putNetworkTunnelConfig(params: { request: TunnelConfigRequest }): Promise<SuccessResponse> {
    return this._doJson<SuccessResponse>({
      method: "PUT",
      pathFmt: "/network/tunnel/config",
      pathArgs: [],
      query: null,
      body: params.request,
      errorCodes: { 400: "ErrorResponse", 422: "ErrorResponse", 500: "ErrorResponse" },
    });
  }

  private async _do(request: ApiRequest): Promise<Response> {
    let path = request.pathFmt.replace(
      /\{\}/g,
      (() => {
        let i = 0;
        return () => encodeURIComponent(request.pathArgs[i++]!);
      })(),
    );
    if (request.query !== null) {
      const search = new URLSearchParams();
      for (const [key, value] of Object.entries(request.query)) {
        // Unset params are omitted so the server applies its default. Arrays
        // are exploded into one repeated param per element; enums and other
        // scalars are stringified as-is.
        if (value === undefined || value === null) continue;
        if (Array.isArray(value)) {
          for (const item of value) search.append(key, String(item));
        } else {
          search.append(key, String(value));
        }
      }
      const qs = search.toString();
      if (qs) path += `?${qs}`;
    }
    const init: RequestInit = {
      method: request.method,
      headers: { ...this.headers },
    };
    const headers = init.headers as Record<string, string>;
    if (request.accept !== undefined) {
      headers["Accept"] = request.accept;
    }
    if (request.body !== null) {
      const contentType = request.bodyContentType ?? "application/json";
      if (contentType === "application/json") {
        headers["Content-Type"] = contentType;
        init.body = JSON.stringify(request.body);
      } else if (contentType === "multipart/form-data") {
        // Left for fetch to set, since only it knows the boundary. An inherited
        // value would suppress that, so drop it, comparing case-insensitively
        // the way header names do.
        for (const key of Object.keys(headers)) {
          if (key.toLowerCase() === "content-type") delete headers[key];
        }
        init.body = request.body as BodyInit;
      } else {
        headers["Content-Type"] = contentType;
        init.body = request.body as BodyInit;
      }
    }
    const response = await this.fetchImpl(`${this.baseUrl}${path}`, init);
    if (!(request.successCodes ?? [200]).includes(response.status)) {
      if (request.errorCodes?.[response.status]) {
        const ErrorClass = ERROR_TYPES[request.errorCodes[response.status]!];
        if (ErrorClass) {
          try {
            const data = await response.json();
            throw new ErrorClass(response.status, data);
          } catch (e) {
            if (Object.values(ERROR_TYPES).some((cls) => e instanceof cls)) throw e;
          }
        }
      }
      throw new ResponseError(response.status, await response.text());
    }
    return response;
  }

  private async _doJson<T>(request: ApiRequest): Promise<T> {
    const response = await this._do(request);
    const contentType = response.headers.get("content-type") || "";
    if (!contentType.includes("application/json")) {
      throw new ResponseError(response.status, `expected a JSON response, got ${contentType}`);
    }
    return (await response.json()) as T;
  }

  /**
   * Reads a JSON body and pairs it with the status, for operations whose
   * success statuses return different types.
   */
  private async _doJsonWithStatus<T>(request: ApiRequest): Promise<{ status: number; data: T }> {
    const response = await this._do(request);
    const contentType = response.headers.get("content-type") || "";
    if (!contentType.includes("application/json")) {
      throw new ResponseError(response.status, `expected a JSON response, got ${contentType}`);
    }
    return { status: response.status, data: (await response.json()) as T };
  }
}
