/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type components = {
  schemas: {
    ApplyEditRequest: {
      /**
       * @example // Add world parameter
       *     function hello(world) {
       *       console.log('Hello', world);
       *     }
       */
      codeEdit: string;
      /** @example relace-apply-3 */
      model?: string;
    };
    ApplyEditResponse: {
      /** @example Code edit applied successfully */
      message?: string;
      /**
       * @example function hello() {
       *       console.log('Hello');
       *     }
       */
      originalContent?: string;
      /** @example src/main.js */
      path?: string;
      /** @example Relace */
      provider?: string;
      /** @example true */
      success?: boolean;
      /**
       * @example function hello(world) {
       *       console.log('Hello', world);
       *     }
       */
      updatedContent?: string;
    };
    ArchiveManifest: {
      /**
       * @description Added and Modified count the archive's payload members.
       * @example 11
       */
      added?: number;
      /**
       * @description APIVersion is the sandbox-api build that produced the archive.
       * @example v0.1.0
       */
      apiVersion?: string;
      createdAt: string;
      /**
       * @description Deleted are paths the image has and the sandbox deleted. Tar cannot carry
       *     a deletion, so import applies these from the manifest.
       */
      deleted?: string[];
      /** @description Excludes are the paths left out of the comparison. */
      excludes?: string[];
      /**
       * @description ImageDevice is the device the pristine image was read from, for the record:
       *     it says where the sandbox that exported the archive found its image.
       * @example /dev/vda
       */
      imageDevice?: string;
      /** @example 3 */
      modified?: number;
      /**
       * @description PayloadBytes is the total content size of the payload members.
       * @example 3073449
       */
      payloadBytes?: number;
      /**
       * @description Processes tells whether ProcessesName is present.
       * @example true
       */
      processes?: boolean;
      /**
       * @description Root is the directory the paths are relative to.
       * @example /
       */
      root: string;
      /** @example 1 */
      version: number;
    };
    ContentSearchMatch: {
      /** @example 10 */
      column: number;
      /**
       * @example previous line
       *     current line
       *     next line
       */
      context?: string;
      /** @example 42 */
      line: number;
      /** @example src/main.go */
      path: string;
      /** @example const searchText = 'example' */
      text: string;
    };
    ContentSearchResponse: {
      matches: components["schemas"]["ContentSearchMatch"][];
      /** @example searchText */
      query: string;
      /** @example 5 */
      total: number;
    };
    Directory: {
      files: components["schemas"]["File"][];
      name: string;
      path: string;
      /** @description @name Subdirectories */
      subdirectories: components["schemas"]["Subdirectory"][];
    };
    DriveListResponse: {
      mounts?: components["schemas"]["DriveMountInfo"][];
    };
    DriveMountInfo: {
      driveName?: string;
      drivePath?: string;
      /** @description The local GID used for this mount */
      gidMap?: string;
      mountPath?: string;
      readOnly?: boolean;
      /** @description The local UID used for this mount */
      uidMap?: string;
    };
    DriveMountRequest: {
      driveName: string;
      /** @description Optional, defaults to "/" */
      drivePath?: string;
      /** @description Optional, local GID to map (filer GID is always 0) */
      gidMap?: string;
      mountPath: string;
      /** @description Optional, defaults to false */
      readOnly?: boolean;
      /** @description Optional, local UID to map (filer UID is always 0) */
      uidMap?: string;
    };
    DriveMountResponse: {
      driveName?: string;
      drivePath?: string;
      /** @description The local GID used for this mount */
      gidMap?: string;
      message?: string;
      mountPath?: string;
      readOnly?: boolean;
      success?: boolean;
      /** @description The local UID used for this mount */
      uidMap?: string;
    };
    DriveUnmountResponse: {
      message?: string;
      mountPath?: string;
      success?: boolean;
    };
    ErrorResponse: {
      /** @example Error message */
      error: string;
    };
    ExportOptions: {
      /**
       * @description Async starts the export and answers immediately, leaving it to run: an
       *     archive of a large filesystem takes longer than a request may be held
       *     open. Its progress is reported by /archive/status.
       * @example false
       */
      async?: boolean;
      /**
       * @description DryRun reports what would be archived, and its exact size, without
       *     stopping anything and without uploading.
       * @example false
       */
      dryRun?: boolean;
      /** @description Excludes are added to the paths excluded by default. */
      excludes?: string[];
      /**
       * @description Headers are sent with the upload request as given. A presigned URL only
       *     accepts the headers it was signed for, so these have to match what the
       *     caller signed: sending one that was not signed, or signing one that is not
       *     sent, is rejected as a signature mismatch. Typical use is a storage class,
       *     x-amz-storage-class: GLACIER_IR.
       */
      headers?: {
        [key: string]: string;
      };
      /**
       * @description ImageDevice is the device holding the pristine image. It is found on its
       *     own, wherever the sandbox booted from attached it, and naming one here
       *     only overrides that.
       * @example /dev/vda
       */
      imageDevice?: string;
      /**
       * @description ImageMountPoint is a directory where the pristine image is already mounted.
       *     When set the image device is neither mounted nor unmounted.
       * @example /mnt/lower
       */
      imageMountPoint?: string;
      /**
       * @description Multipart uploads the archive part by part instead, which is how an
       *     archive larger than the 5 GB a single PUT accepts is stored. It takes
       *     precedence over URL.
       */
      multipart?: components["schemas"]["MultipartUpload"];
      /**
       * @description SaveProcesses stores the process list in the archive so restore can
       *     relaunch the workload. Defaults to true; set it to false to archive
       *     storage only.
       * @example true
       */
      saveProcesses?: boolean;
      /**
       * @description StopTimeoutSeconds bounds the graceful stop of each process.
       * @example 30
       */
      stopTimeoutSeconds?: number;
      /**
       * @description URL is a presigned S3 PUT URL the archive is streamed to. Empty is only
       *     valid with DryRun, or with Multipart.
       * @example https://bucket.s3.amazonaws.com/key?...
       */
      url?: string;
    };
    ExportProgress: {
      /** @description Error is why the export failed, without the presigned URL it used. */
      error?: string;
      finishedAt?: string;
      /**
       * @description Size is the archive's exact size, known once the filesystem is scanned.
       * @example 3074211
       */
      size?: number;
      startedAt?: string;
      /** @example running */
      state?: components["schemas"]["ArchiveExportState"];
      /**
       * @description Uploaded reports whether the storage holds the archive.
       * @example false
       */
      uploaded?: boolean;
    };
    ExportResult: {
      /**
       * @description Changes lists every path in the archive. Only filled for a dry run,
       *     where it is the point of the call.
       */
      changes?: components["schemas"]["ArchiveChange"][];
      /** @example 4.2s */
      duration?: string;
      manifest: components["schemas"]["ArchiveManifest"];
      /**
       * @description Size is the exact number of bytes uploaded, known before the upload
       *     starts since the archive is not compressed.
       * @example 3074211
       */
      size?: number;
      /** @description StoppedProcesses are the processes stopped to freeze the filesystem. */
      stoppedProcesses?: string[];
      /**
       * @description Uploaded is false for a dry run.
       * @example true
       */
      uploaded?: boolean;
    };
    File: {
      group: string;
      lastModified: string;
      name: string;
      owner: string;
      path: string;
      permissions: string;
      size: number;
    };
    FileRequest: {
      /** @example file contents here */
      content?: string;
      /** @example false */
      isDirectory?: boolean;
      /** @example 0644 */
      permissions?: string;
    };
    FileWithContent: {
      content: string;
      group: string;
      lastModified: string;
      name: string;
      owner: string;
      path: string;
      permissions: string;
      size: number;
    };
    FindMatch: {
      /** @example src/main.go */
      path: string;
      /**
       * @description "file" or "directory"
       * @example file
       */
      type: string;
    };
    FindResponse: {
      matches: components["schemas"]["FindMatch"][];
      /** @example 5 */
      total: number;
    };
    FuzzySearchMatch: {
      /** @example src/main.go */
      path: string;
      /** @example 100 */
      score: number;
      /**
       * @description "file" or "directory"
       * @example file
       */
      type: string;
    };
    FuzzySearchResponse: {
      matches: components["schemas"]["FuzzySearchMatch"][];
      /** @example 5 */
      total: number;
    };
    HealthResponse: {
      /** @example amd64 */
      arch: string;
      /** @example 2026-01-29T17:36:52Z */
      buildTime: string;
      /** @example abc123 */
      gitCommit: string;
      /** @example go1.25.0 */
      goVersion: string;
      lastUpgrade: components["schemas"]["UpgradeStatus"];
      /** @example linux */
      os: string;
      /** @example 2026-01-29T18:45:49Z */
      startedAt: string;
      /** @example ok */
      status: string;
      /** @example 0 */
      upgradeCount: number;
      /** @example 1h30m */
      uptime: string;
      /** @example 5400.5 */
      uptimeSeconds: number;
      /** @example v0.1.0 */
      version: string;
    };
    MultipartCompleteRequest: {
      parts?: components["schemas"]["MultipartPartInfo"][];
    };
    MultipartInitiateRequest: {
      /** @example 0644 */
      permissions?: string;
    };
    MultipartInitiateResponse: {
      /** @example /tmp/largefile.dat */
      path?: string;
      /** @example 550e8400-e29b-41d4-a716-446655440000 */
      uploadId?: string;
    };
    MultipartListPartsResponse: {
      parts?: components["schemas"]["FilesystemUploadedPart"][];
      /** @example 550e8400-e29b-41d4-a716-446655440000 */
      uploadId?: string;
    };
    MultipartListUploadsResponse: {
      uploads?: components["schemas"]["FilesystemMultipartUpload"][];
    };
    MultipartPartInfo: {
      /** @example 5d41402abc4b2a76b9719d911017c592 */
      etag?: string;
      /** @example 1 */
      partNumber?: number;
    };
    MultipartUpload: {
      /**
       * @description AbortURL is a presigned DELETE URL that discards the parts already
       *     uploaded. Without it a failed export leaves them on the storage until a
       *     lifecycle rule removes them.
       */
      abortUrl?: string;
      /** @description CompleteURL is a presigned POST URL that assembles the parts. */
      completeUrl?: string;
      /**
       * @description PartSize is the number of bytes sent to every part but the last.
       * @example 536870912
       */
      partSize?: number;
      /**
       * @description PartURLs are presigned PUT URLs, one per part, in order. Extra ones are
       *     left unused.
       */
      partUrls?: string[];
    };
    MultipartUploadPartResponse: {
      /** @example 5d41402abc4b2a76b9719d911017c592 */
      etag?: string;
      /** @example 1 */
      partNumber?: number;
      /** @example 5242880 */
      size?: number;
    };
    PortMonitorRequest: {
      /**
       * @description URL to call when a new port is detected
       * @example http://localhost:3000/callback
       */
      callback?: string;
    };
    ProcessLogs: {
      /** @example logs output */
      logs: string;
      /** @example stderr output */
      stderr: string;
      /** @example stdout output */
      stdout: string;
    };
    ProcessRequest: {
      /** @example ls -la */
      command: string;
      /**
       * @example {
       *       "{\"PORT\"": " \"3000\"}"
       *     }
       */
      env?: {
        [key: string]: string;
      };
      /**
       * @description Disable scale-to-zero while process runs. Default timeout is 600s (10 minutes). Set timeout to 0 for infinite.
       * @example false
       */
      keepAlive?: boolean;
      /**
       * @description Maximum number of restarts on failure. Set to a negative value (e.g. -1) for unlimited restarts.
       * @example 3
       */
      maxRestarts?: number;
      /** @example my-process */
      name?: string;
      /** @example true */
      restartOnFailure?: boolean;
      /**
       * @description Open a writable stdin pipe, fed via POST /process/{identifier}/stdin and closed via DELETE. The pipe does not survive a sandbox-api restart: the process then sees EOF.
       * @example false
       */
      stdin?: boolean;
      /**
       * @description Timeout in seconds. When keepAlive is true, defaults to 600s (10 minutes). Set to 0 for infinite (no auto-kill).
       * @example 30
       */
      timeout?: number;
      /** @example false */
      waitForCompletion?: boolean;
      /**
       * @example [
       *       3000,
       *       8080
       *     ]
       */
      waitForPorts?: number[];
      /** @example /home/user */
      workingDir?: string;
    };
    ProcessResponse: {
      /** @example ls -la */
      command: string;
      /** @example Wed, 01 Jan 2023 12:01:00 GMT */
      completedAt: string;
      /** @example 0 */
      exitCode: number;
      /**
       * @description Whether scale-to-zero is disabled for this process
       * @example false
       */
      keepAlive?: boolean;
      /** @example logs output */
      logs: string;
      /** @example 3 */
      maxRestarts?: number;
      /** @example my-process */
      name: string;
      /** @example 1234 */
      pid: string;
      /** @example 2 */
      restartCount?: number;
      /** @example true */
      restartOnFailure?: boolean;
      /** @example Wed, 01 Jan 2023 12:00:00 GMT */
      startedAt: string;
      /**
       * @example running
       * @enum {string}
       */
      status: "failed" | "killed" | "stopped" | "running" | "completed";
      /** @example stderr output */
      stderr: string;
      /**
       * @description Whether the process was started with a writable stdin pipe
       * @example false
       */
      stdin?: boolean;
      /** @example stdout output */
      stdout: string;
      /** @example /home/user */
      workingDir: string;
    };
    QuiesceStatus: {
      /**
       * @description Export reports the export started asynchronously, if there was one. It is
       *     how a caller that did not wait for the export learns that the archive is
       *     on the storage, or why it is not.
       */
      export?: components["schemas"]["ExportProgress"];
      /**
       * @description ReadOnlyRoot reports whether the root mount was remounted read-only, which
       *     is what actually stops writes; false means the freeze relies only on the
       *     API refusing calls, and the reason says why.
       * @example true
       */
      readOnlyRoot?: boolean;
      /**
       * @description Reason is a human readable explanation of why the sandbox is frozen.
       * @example archive export
       */
      reason?: string;
      /**
       * @description Restore reports the archive this sandbox was started from, if it was
       *     started from one: how far its restore has got, and how it ended.
       */
      restore?: components["schemas"]["RestoreProgress"];
      /** @description Since is when the sandbox left StateActive. */
      since?: string;
      /** @example quiesced */
      state: components["schemas"]["ArchiveQuiesceState"];
      /** @description StoppedProcesses are the process identifiers stopped while quiescing. */
      stoppedProcesses?: string[];
    };
    RankedFile: {
      content?: string;
      path?: string;
      score?: number;
    };
    RerankingResponse: {
      files?: components["schemas"]["RankedFile"][];
      /** @example Found 5 relevant files */
      message?: string;
      /** @example true */
      success?: boolean;
    };
    RestoreProgress: {
      /** @example 3 */
      deleted?: number;
      /**
       * @description Downloaded is how much of the archive has been read so far.
       * @example 1048576
       */
      downloaded?: number;
      /** @description Error is why the restore failed, without the presigned URL it used. */
      error?: string;
      finishedAt?: string;
      /**
       * @description Restored and Deleted count what the archive changed on the filesystem.
       * @example 1204
       */
      restored?: number;
      /**
       * @description Size is the archive's size as the storage announced it, and zero when it
       *     announced none - a client showing a percentage has to allow for that.
       * @example 3074211
       */
      size?: number;
      startedAt?: string;
      /** @example extracting */
      state?: components["schemas"]["ArchiveRestoreState"];
    };
    Subdirectory: {
      name: string;
      path: string;
    };
    SuccessResponse: {
      /** @example File created successfully */
      message: string;
      /** @example /path/to/file */
      path?: string;
    };
    TreeRequest: {
      /**
       * @example {
       *       "\"dir/file2.txt\"": "\"content2\"}",
       *       "{\"file1.txt\"": "\"content1\""
       *     }
       */
      files?: {
        [key: string]: string;
      };
    };
    TunnelConfigRequest: {
      /**
       * @description Base64-encoded tunnel config JSON
       * @example eyJsb2NhbF9pcCI6ICIxMC4wLjAuMS8zMiIsIC4uLn0=
       */
      config: string;
    };
    UpgradeRequest: {
      /**
       * @description Base URL for releases (useful for forks)
       * @example https://github.com/blaxel-ai/sandbox/releases
       */
      baseUrl?: string;
      /**
       * @description Version to upgrade to: "latest" (default), "develop", "main", or specific tag like "v1.0.0"
       * @example latest
       */
      version?: string;
    };
    UpgradeStatus: {
      /**
       * @description Path to downloaded binary
       * @example /tmp/sandbox-api-new
       */
      binaryPath?: string;
      /**
       * @description Bytes downloaded
       * @example 25034936
       */
      bytesDownloaded?: number;
      /**
       * @description URL used for download
       * @example https://github.com/...
       */
      downloadUrl?: string;
      /**
       * @description Error message if failed
       * @example Failed to download binary
       */
      error?: string;
      /** @description When the upgrade was attempted */
      lastAttempt?: string;
      /**
       * @description Current state (idle, running, completed, failed)
       * @example running
       */
      status: components["schemas"]["ProcessUpgradeState"];
      /**
       * @description Current/last step (none, starting, download, validate, replace, completed, skipped)
       * @example download
       */
      step: string;
      /**
       * @description Version being upgraded to
       * @example latest
       */
      version: string;
    };
    ArchiveChange: {
      /** @example added */
      kind: components["schemas"]["ArchiveChangeKind"];
      /**
       * @description Path is relative to the root, without a leading slash.
       * @example usr/bin/curl
       */
      path: string;
      /**
       * @description Size is the file content size in bytes, 0 for anything but a regular file.
       * @example 256216
       */
      size?: number;
    };
    /** @enum {string} */
    ArchiveChangeKind: "added" | "modified" | "deleted";
    /** @enum {string} */
    ArchiveExportState: "running" | "succeeded" | "failed";
    /** @enum {string} */
    ArchiveQuiesceState: "active" | "quiescing" | "quiesced" | "restoring";
    /** @enum {string} */
    ArchiveRestoreState: "downloading" | "extracting" | "relaunching" | "succeeded" | "failed";
    FilesystemMultipartUpload: {
      initiatedAt?: string;
      parts?: {
        [key: string]: components["schemas"]["FilesystemUploadedPart"];
      };
      /** @example /tmp/largefile.dat */
      path?: string;
      /** @example 420 */
      permissions?: number;
      /** @example 550e8400-e29b-41d4-a716-446655440000 */
      uploadId?: string;
    };
    FilesystemUploadedPart: {
      /** @example 5d41402abc4b2a76b9719d911017c592 */
      etag?: string;
      /** @example 1 */
      partNumber?: number;
      /** @example 5242880 */
      size?: number;
      uploadedAt?: string;
    };
    HandlerReloadResponse: {
      applied?: number;
      generation?: number;
      removed?: number;
    };
    /** @enum {string} */
    ProcessUpgradeState: "idle" | "running" | "completed" | "failed";
    GetCodegenRerankingQuery: {
      /** @description Natural language query to search for */
      query: string;
      /** @description Minimum relevance score (default: 0.5) */
      scoreThreshold?: number;
      /** @description Maximum tokens to return (default: 30000) */
      tokenLimit?: number;
      /** @description Regex pattern to filter files (e.g., .*\\.ts$ for TypeScript files) */
      filePattern?: string;
    };
    GetFilesystemContentSearchQuery: {
      /** @description Text to search for */
      query: string;
      /** @description Case sensitive search (default: false) */
      caseSensitive?: boolean;
      /** @description Maximum number of results to return (default: 100) */
      maxResults?: number;
      /** @description File pattern to include (e.g., *.go) */
      filePattern?: string;
      /** @description Comma-separated directory names to skip (default: node_modules,vendor,.git,dist,build,target,__pycache__,.venv,.next,coverage) */
      excludeDirs?: string;
    };
    GetFilesystemFindQuery: {
      /** @description Type of search (file or directory) */
      type?: string;
      /** @description Comma-separated file patterns to include (e.g., *.go,*.js) */
      patterns?: string;
      /** @description Maximum number of results to return (default: 20). If set to 0, all results will be returned. */
      maxResults?: number;
      /** @description Comma-separated directory names to skip (default: node_modules,vendor,.git,dist,build,target,__pycache__,.venv,.next,coverage). Use empty string to skip no directories. */
      excludeDirs?: string;
      /** @description Exclude hidden files and directories (default: true) */
      excludeHidden?: boolean;
    };
    PutFilesystemMultipartPartQuery: {
      /** @description Part number (1-10000) */
      partNumber: number;
    };
    GetFilesystemSearchQuery: {
      /** @description Maximum number of results to return (default: 20) */
      maxResults?: number;
      /** @description Comma-separated file patterns to include (e.g., *.go,*.js) */
      patterns?: string;
      /** @description Comma-separated directory names to skip (default: node_modules,vendor,.git,dist,build,target,__pycache__,.venv,.next,coverage). Use empty string to skip no directories. */
      excludeDirs?: string;
      /** @description Exclude hidden files and directories (default: true) */
      excludeHidden?: boolean;
    };
    DeleteFilesystemQuery: {
      /** @description Delete directory recursively */
      recursive?: boolean;
    };
    GetFilesystemQuery: {
      /** @description Force download mode for files */
      download?: boolean;
    };
    DeleteFilesystemTreeQuery: {
      /** @description Delete directory recursively */
      recursive?: boolean;
    };
    GetWatchFilesystemQuery: {
      /** @description Ignore patterns (comma-separated) */
      ignore?: string;
    };
    GetFilesystemResponse:
      | components["schemas"]["Directory"]
      | components["schemas"]["FileWithContent"]
      | string;
    GetFilesystemTreeResponse:
      | components["schemas"]["Directory"]
      | components["schemas"]["FileWithContent"]
      | string;
    PutFilesystemTreeResponse:
      | components["schemas"]["Directory"]
      | components["schemas"]["FileWithContent"]
      | string;
    DeleteNetworkProcessMonitorResponse: {
      [key: string]: unknown;
    };
    PostNetworkProcessMonitorResponse: {
      [key: string]: unknown;
    };
    GetNetworkProcessPortsResponse: {
      [key: string]: unknown;
    };
    GetProcessResponse: components["schemas"]["ProcessResponse"][];
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
};
export type ApplyEditRequest = components["schemas"]["ApplyEditRequest"];
export type ApplyEditResponse = components["schemas"]["ApplyEditResponse"];
export type ArchiveManifest = components["schemas"]["ArchiveManifest"];
export type ContentSearchMatch = components["schemas"]["ContentSearchMatch"];
export type ContentSearchResponse = components["schemas"]["ContentSearchResponse"];
export type Directory = components["schemas"]["Directory"];
export type DriveListResponse = components["schemas"]["DriveListResponse"];
export type DriveMountInfo = components["schemas"]["DriveMountInfo"];
export type DriveMountRequest = components["schemas"]["DriveMountRequest"];
export type DriveMountResponse = components["schemas"]["DriveMountResponse"];
export type DriveUnmountResponse = components["schemas"]["DriveUnmountResponse"];
export type ErrorResponse = components["schemas"]["ErrorResponse"];
export type ExportOptions = components["schemas"]["ExportOptions"];
export type ExportProgress = components["schemas"]["ExportProgress"];
export type ExportResult = components["schemas"]["ExportResult"];
export type File = components["schemas"]["File"];
export type FileRequest = components["schemas"]["FileRequest"];
export type FileWithContent = components["schemas"]["FileWithContent"];
export type FindMatch = components["schemas"]["FindMatch"];
export type FindResponse = components["schemas"]["FindResponse"];
export type FuzzySearchMatch = components["schemas"]["FuzzySearchMatch"];
export type FuzzySearchResponse = components["schemas"]["FuzzySearchResponse"];
export type HealthResponse = components["schemas"]["HealthResponse"];
export type MultipartCompleteRequest = components["schemas"]["MultipartCompleteRequest"];
export type MultipartInitiateRequest = components["schemas"]["MultipartInitiateRequest"];
export type MultipartInitiateResponse = components["schemas"]["MultipartInitiateResponse"];
export type MultipartListPartsResponse = components["schemas"]["MultipartListPartsResponse"];
export type MultipartListUploadsResponse = components["schemas"]["MultipartListUploadsResponse"];
export type MultipartPartInfo = components["schemas"]["MultipartPartInfo"];
export type MultipartUpload = components["schemas"]["MultipartUpload"];
export type MultipartUploadPartResponse = components["schemas"]["MultipartUploadPartResponse"];
export type PortMonitorRequest = components["schemas"]["PortMonitorRequest"];
export type ProcessLogs = components["schemas"]["ProcessLogs"];
export type ProcessRequest = components["schemas"]["ProcessRequest"];
export type ProcessResponse = components["schemas"]["ProcessResponse"];
export type QuiesceStatus = components["schemas"]["QuiesceStatus"];
export type RankedFile = components["schemas"]["RankedFile"];
export type RerankingResponse = components["schemas"]["RerankingResponse"];
export type RestoreProgress = components["schemas"]["RestoreProgress"];
export type Subdirectory = components["schemas"]["Subdirectory"];
export type SuccessResponse = components["schemas"]["SuccessResponse"];
export type TreeRequest = components["schemas"]["TreeRequest"];
export type TunnelConfigRequest = components["schemas"]["TunnelConfigRequest"];
export type UpgradeRequest = components["schemas"]["UpgradeRequest"];
export type UpgradeStatus = components["schemas"]["UpgradeStatus"];
export type ArchiveChange = components["schemas"]["ArchiveChange"];
export type ArchiveChangeKind = components["schemas"]["ArchiveChangeKind"];
export type ArchiveExportState = components["schemas"]["ArchiveExportState"];
export type ArchiveQuiesceState = components["schemas"]["ArchiveQuiesceState"];
export type ArchiveRestoreState = components["schemas"]["ArchiveRestoreState"];
export type FilesystemMultipartUpload = components["schemas"]["FilesystemMultipartUpload"];
export type FilesystemUploadedPart = components["schemas"]["FilesystemUploadedPart"];
export type HandlerReloadResponse = components["schemas"]["HandlerReloadResponse"];
export type ProcessUpgradeState = components["schemas"]["ProcessUpgradeState"];
export type GetCodegenRerankingQuery = components["schemas"]["GetCodegenRerankingQuery"];
export type GetFilesystemContentSearchQuery =
  components["schemas"]["GetFilesystemContentSearchQuery"];
export type GetFilesystemFindQuery = components["schemas"]["GetFilesystemFindQuery"];
export type PutFilesystemMultipartPartQuery =
  components["schemas"]["PutFilesystemMultipartPartQuery"];
export type GetFilesystemSearchQuery = components["schemas"]["GetFilesystemSearchQuery"];
export type DeleteFilesystemQuery = components["schemas"]["DeleteFilesystemQuery"];
export type GetFilesystemQuery = components["schemas"]["GetFilesystemQuery"];
export type DeleteFilesystemTreeQuery = components["schemas"]["DeleteFilesystemTreeQuery"];
export type GetWatchFilesystemQuery = components["schemas"]["GetWatchFilesystemQuery"];
export type GetFilesystemResponse = components["schemas"]["GetFilesystemResponse"];
export type GetFilesystemTreeResponse = components["schemas"]["GetFilesystemTreeResponse"];
export type PutFilesystemTreeResponse = components["schemas"]["PutFilesystemTreeResponse"];
export type DeleteNetworkProcessMonitorResponse =
  components["schemas"]["DeleteNetworkProcessMonitorResponse"];
export type PostNetworkProcessMonitorResponse =
  components["schemas"]["PostNetworkProcessMonitorResponse"];
export type GetNetworkProcessPortsResponse =
  components["schemas"]["GetNetworkProcessPortsResponse"];
export type GetProcessResponse = components["schemas"]["GetProcessResponse"];
