// Code generated by apigen/clientgen. DO NOT EDIT.

import type {
  AsyncPredictOutput,
  AsyncPredictRequest,
  AsyncRequestStatusResponse,
  AsyncRunRemoteInput,
  AsyncRunRemoteOutput,
  CancelAsyncRequestOutput,
  ErrorResponse,
  GetAsyncQueueStatusOutput,
  PredictInput,
  PredictOutput,
  RunRemoteInput,
  RunRemoteOutput,
} from "./models.gen";

export class ResponseError extends Error {
  constructor(
    public readonly statusCode: number,
    public readonly body: string,
  ) {
    super(`baseten API error (HTTP ${statusCode}): ${body}`);
  }
}

export class ResponseErrorResponse extends Error {
  public readonly error_response: ErrorResponse;
  constructor(statusCode: number, data: unknown) {
    super(`baseten API error (HTTP ${statusCode}): ${JSON.stringify(data)}`);
    this.error_response = data as ErrorResponse;
  }
}

const ERROR_TYPES: Record<string, new (statusCode: number, data: unknown) => Error> = {
  ErrorResponse: ResponseErrorResponse,
};

interface ApiRequest {
  method: string;
  pathFmt: string;
  pathArgs: string[];
  body: unknown;
  successCode: number;
  errorCodes: Record<number, string> | null;
}

export class ApiClient {
  /**
   * Generated HTTP client for the Baseten API.
   *
   * Methods on this client are generated from the OpenAPI specification
   * and are NOT covered by any stability or compatibility guarantees.
   * They may change without notice between versions.
   */
  private readonly baseUrl: string;
  private readonly headers: Record<string, string>;
  private readonly fetchImpl: typeof fetch;

  constructor(options: { baseUrl: string; headers: Record<string, string>; fetch?: typeof fetch }) {
    this.baseUrl = options.baseUrl;
    this.headers = options.headers;
    this.fetchImpl = options.fetch ?? globalThis.fetch;
  }

  /** Asynchronously call a named environment of a model. */
  async asyncPredict(params: {
    env_name: string;
    body: AsyncPredictRequest;
  }): Promise<AsyncPredictOutput> {
    return this._doJson<AsyncPredictOutput>({
      method: "POST",
      pathFmt: "/environments/{}/async_predict",
      pathArgs: [params.env_name],
      body: params.body,
      successCode: 201,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        413: "ErrorResponse",
        429: "ErrorResponse",
        503: "ErrorResponse",
      },
    });
  }

  /** Asynchronously call a specific deployment of a model. */
  async asyncPredictDeployment(params: {
    deployment_id: string;
    body: AsyncPredictRequest;
  }): Promise<AsyncPredictOutput> {
    return this._doJson<AsyncPredictOutput>({
      method: "POST",
      pathFmt: "/deployment/{}/async_predict",
      pathArgs: [params.deployment_id],
      body: params.body,
      successCode: 201,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        413: "ErrorResponse",
        429: "ErrorResponse",
        503: "ErrorResponse",
      },
    });
  }

  /** Asynchronously call the development deployment of a model. */
  async asyncPredictDevelopment(params: {
    body: AsyncPredictRequest;
  }): Promise<AsyncPredictOutput> {
    return this._doJson<AsyncPredictOutput>({
      method: "POST",
      pathFmt: "/development/async_predict",
      pathArgs: [],
      body: params.body,
      successCode: 201,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        413: "ErrorResponse",
        429: "ErrorResponse",
        503: "ErrorResponse",
      },
    });
  }

  /** Asynchronously call the production environment of a model. */
  async asyncPredictProduction(params: { body: AsyncPredictRequest }): Promise<AsyncPredictOutput> {
    return this._doJson<AsyncPredictOutput>({
      method: "POST",
      pathFmt: "/production/async_predict",
      pathArgs: [],
      body: params.body,
      successCode: 201,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        413: "ErrorResponse",
        429: "ErrorResponse",
        503: "ErrorResponse",
      },
    });
  }

  /** Asynchronously call a regional environment of a model. */
  async asyncPredictRegional(params: { body: AsyncPredictRequest }): Promise<AsyncPredictOutput> {
    return this._doJson<AsyncPredictOutput>({
      method: "POST",
      pathFmt: "/async_predict",
      pathArgs: [],
      body: params.body,
      successCode: 201,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        413: "ErrorResponse",
        429: "ErrorResponse",
        503: "ErrorResponse",
      },
    });
  }

  /** Asynchronously call a named environment of a chain. */
  async asyncRunRemote(params: {
    env_name: string;
    body: AsyncRunRemoteInput;
  }): Promise<AsyncRunRemoteOutput> {
    return this._doJson<AsyncRunRemoteOutput>({
      method: "POST",
      pathFmt: "/environments/{}/async_run_remote",
      pathArgs: [params.env_name],
      body: params.body,
      successCode: 201,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        429: "ErrorResponse",
        503: "ErrorResponse",
      },
    });
  }

  /** Asynchronously call a specific deployment of a chain. */
  async asyncRunRemoteDeployment(params: {
    deployment_id: string;
    body: AsyncRunRemoteInput;
  }): Promise<AsyncRunRemoteOutput> {
    return this._doJson<AsyncRunRemoteOutput>({
      method: "POST",
      pathFmt: "/deployment/{}/async_run_remote",
      pathArgs: [params.deployment_id],
      body: params.body,
      successCode: 201,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        429: "ErrorResponse",
        503: "ErrorResponse",
      },
    });
  }

  /** Asynchronously call the development deployment of a chain. */
  async asyncRunRemoteDevelopment(params: {
    body: AsyncRunRemoteInput;
  }): Promise<AsyncRunRemoteOutput> {
    return this._doJson<AsyncRunRemoteOutput>({
      method: "POST",
      pathFmt: "/development/async_run_remote",
      pathArgs: [],
      body: params.body,
      successCode: 201,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        429: "ErrorResponse",
        503: "ErrorResponse",
      },
    });
  }

  /** Asynchronously call the production environment of a chain. */
  async asyncRunRemoteProduction(params: {
    body: AsyncRunRemoteInput;
  }): Promise<AsyncRunRemoteOutput> {
    return this._doJson<AsyncRunRemoteOutput>({
      method: "POST",
      pathFmt: "/production/async_run_remote",
      pathArgs: [],
      body: params.body,
      successCode: 201,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        429: "ErrorResponse",
        503: "ErrorResponse",
      },
    });
  }

  /** Asynchronously call a regional environment of a chain. */
  async asyncRunRemoteRegional(params: {
    body: AsyncRunRemoteInput;
  }): Promise<AsyncRunRemoteOutput> {
    return this._doJson<AsyncRunRemoteOutput>({
      method: "POST",
      pathFmt: "/async_run_remote",
      pathArgs: [],
      body: params.body,
      successCode: 201,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        429: "ErrorResponse",
        503: "ErrorResponse",
      },
    });
  }

  /** Cancel a queued async request. */
  async cancelAsyncRequest(params: { request_id: string }): Promise<CancelAsyncRequestOutput> {
    return this._doJson<CancelAsyncRequestOutput>({
      method: "DELETE",
      pathFmt: "/async_request/{}",
      pathArgs: [params.request_id],
      body: null,
      successCode: 200,
      errorCodes: { 401: "ErrorResponse", 429: "ErrorResponse" },
    });
  }

  /** Get async queue status for a named environment. */
  async getAsyncQueueStatus(params: { env_name: string }): Promise<GetAsyncQueueStatusOutput> {
    return this._doJson<GetAsyncQueueStatusOutput>({
      method: "GET",
      pathFmt: "/environments/{}/async_queue_status",
      pathArgs: [params.env_name],
      body: null,
      successCode: 200,
      errorCodes: { 401: "ErrorResponse", 429: "ErrorResponse" },
    });
  }

  /** Get async queue status for a specific deployment. */
  async getAsyncQueueStatusDeployment(params: {
    deployment_id: string;
  }): Promise<GetAsyncQueueStatusOutput> {
    return this._doJson<GetAsyncQueueStatusOutput>({
      method: "GET",
      pathFmt: "/deployment/{}/async_queue_status",
      pathArgs: [params.deployment_id],
      body: null,
      successCode: 200,
      errorCodes: { 401: "ErrorResponse", 429: "ErrorResponse" },
    });
  }

  /** Get async queue status for the development deployment. */
  async getAsyncQueueStatusDevelopment(): Promise<GetAsyncQueueStatusOutput> {
    return this._doJson<GetAsyncQueueStatusOutput>({
      method: "GET",
      pathFmt: "/development/async_queue_status",
      pathArgs: [],
      body: null,
      successCode: 200,
      errorCodes: { 401: "ErrorResponse", 429: "ErrorResponse" },
    });
  }

  /** Get async queue status for the production environment. */
  async getAsyncQueueStatusProduction(): Promise<GetAsyncQueueStatusOutput> {
    return this._doJson<GetAsyncQueueStatusOutput>({
      method: "GET",
      pathFmt: "/production/async_queue_status",
      pathArgs: [],
      body: null,
      successCode: 200,
      errorCodes: { 401: "ErrorResponse", 429: "ErrorResponse" },
    });
  }

  /** Get async queue status for a regional environment. */
  async getAsyncQueueStatusRegional(): Promise<GetAsyncQueueStatusOutput> {
    return this._doJson<GetAsyncQueueStatusOutput>({
      method: "GET",
      pathFmt: "/async_queue_status",
      pathArgs: [],
      body: null,
      successCode: 200,
      errorCodes: { 401: "ErrorResponse", 429: "ErrorResponse" },
    });
  }

  /** Get the status of an async request. */
  async getAsyncRequestStatus(params: { request_id: string }): Promise<AsyncRequestStatusResponse> {
    return this._doJson<AsyncRequestStatusResponse>({
      method: "GET",
      pathFmt: "/async_request/{}",
      pathArgs: [params.request_id],
      body: null,
      successCode: 200,
      errorCodes: { 401: "ErrorResponse", 429: "ErrorResponse" },
    });
  }

  /** Call the model deployment associated with a specified environment. */
  async predict(params: { env_name: string; body: PredictInput }): Promise<PredictOutput> {
    return this._doJson<PredictOutput>({
      method: "POST",
      pathFmt: "/environments/{}/predict",
      pathArgs: [params.env_name],
      body: params.body,
      successCode: 200,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        429: "ErrorResponse",
        502: "ErrorResponse",
        503: "ErrorResponse",
        504: "ErrorResponse",
      },
    });
  }

  /** Call a specific deployment of a model by deployment ID. */
  async predictDeployment(params: {
    deployment_id: string;
    body: PredictInput;
  }): Promise<PredictOutput> {
    return this._doJson<PredictOutput>({
      method: "POST",
      pathFmt: "/deployment/{}/predict",
      pathArgs: [params.deployment_id],
      body: params.body,
      successCode: 200,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        429: "ErrorResponse",
        502: "ErrorResponse",
        503: "ErrorResponse",
        504: "ErrorResponse",
      },
    });
  }

  /** Call the development deployment of a model. */
  async predictDevelopment(params: { body: PredictInput }): Promise<PredictOutput> {
    return this._doJson<PredictOutput>({
      method: "POST",
      pathFmt: "/development/predict",
      pathArgs: [],
      body: params.body,
      successCode: 200,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        429: "ErrorResponse",
        502: "ErrorResponse",
        503: "ErrorResponse",
        504: "ErrorResponse",
      },
    });
  }

  /** Call the production environment of a model. */
  async predictProduction(params: { body: PredictInput }): Promise<PredictOutput> {
    return this._doJson<PredictOutput>({
      method: "POST",
      pathFmt: "/production/predict",
      pathArgs: [],
      body: params.body,
      successCode: 200,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        429: "ErrorResponse",
        502: "ErrorResponse",
        503: "ErrorResponse",
        504: "ErrorResponse",
      },
    });
  }

  /** Call a regional environment of a model. */
  async predictRegional(params: { body: PredictInput }): Promise<PredictOutput> {
    return this._doJson<PredictOutput>({
      method: "POST",
      pathFmt: "/predict",
      pathArgs: [],
      body: params.body,
      successCode: 200,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        429: "ErrorResponse",
        502: "ErrorResponse",
        503: "ErrorResponse",
        504: "ErrorResponse",
      },
    });
  }

  /** Call the chain deployment associated with a specified environment. */
  async runRemote(params: { env_name: string; body: RunRemoteInput }): Promise<RunRemoteOutput> {
    return this._doJson<RunRemoteOutput>({
      method: "POST",
      pathFmt: "/environments/{}/run_remote",
      pathArgs: [params.env_name],
      body: params.body,
      successCode: 200,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        429: "ErrorResponse",
        502: "ErrorResponse",
        503: "ErrorResponse",
        504: "ErrorResponse",
      },
    });
  }

  /** Call a specific chain deployment by deployment ID. */
  async runRemoteDeployment(params: {
    deployment_id: string;
    body: RunRemoteInput;
  }): Promise<RunRemoteOutput> {
    return this._doJson<RunRemoteOutput>({
      method: "POST",
      pathFmt: "/deployment/{}/run_remote",
      pathArgs: [params.deployment_id],
      body: params.body,
      successCode: 200,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        429: "ErrorResponse",
        502: "ErrorResponse",
        503: "ErrorResponse",
        504: "ErrorResponse",
      },
    });
  }

  /** Call the development deployment of a chain. */
  async runRemoteDevelopment(params: { body: RunRemoteInput }): Promise<RunRemoteOutput> {
    return this._doJson<RunRemoteOutput>({
      method: "POST",
      pathFmt: "/development/run_remote",
      pathArgs: [],
      body: params.body,
      successCode: 200,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        429: "ErrorResponse",
        502: "ErrorResponse",
        503: "ErrorResponse",
        504: "ErrorResponse",
      },
    });
  }

  /** Call the production environment of a chain. */
  async runRemoteProduction(params: { body: RunRemoteInput }): Promise<RunRemoteOutput> {
    return this._doJson<RunRemoteOutput>({
      method: "POST",
      pathFmt: "/production/run_remote",
      pathArgs: [],
      body: params.body,
      successCode: 200,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        429: "ErrorResponse",
        502: "ErrorResponse",
        503: "ErrorResponse",
        504: "ErrorResponse",
      },
    });
  }

  /** Call a regional environment of a chain. */
  async runRemoteRegional(params: { body: RunRemoteInput }): Promise<RunRemoteOutput> {
    return this._doJson<RunRemoteOutput>({
      method: "POST",
      pathFmt: "/run_remote",
      pathArgs: [],
      body: params.body,
      successCode: 200,
      errorCodes: {
        400: "ErrorResponse",
        401: "ErrorResponse",
        429: "ErrorResponse",
        502: "ErrorResponse",
        503: "ErrorResponse",
        504: "ErrorResponse",
      },
    });
  }

  /** Wake a named environment of a model. */
  async wake(params: { env_name: string }): Promise<void> {
    await this._doNoResponse({
      method: "POST",
      pathFmt: "/environments/{}/wake",
      pathArgs: [params.env_name],
      body: null,
      successCode: 202,
      errorCodes: { 401: "ErrorResponse" },
    });
  }

  /** Wake a specific deployment of a model by deployment ID. */
  async wakeDeployment(params: { deployment_id: string }): Promise<void> {
    await this._doNoResponse({
      method: "POST",
      pathFmt: "/deployment/{}/wake",
      pathArgs: [params.deployment_id],
      body: null,
      successCode: 202,
      errorCodes: { 401: "ErrorResponse" },
    });
  }

  /** Wake the development deployment of a model. */
  async wakeDevelopment(): Promise<void> {
    await this._doNoResponse({
      method: "POST",
      pathFmt: "/development/wake",
      pathArgs: [],
      body: null,
      successCode: 202,
      errorCodes: { 401: "ErrorResponse" },
    });
  }

  /** Wake the production environment of a model. */
  async wakeProduction(): Promise<void> {
    await this._doNoResponse({
      method: "POST",
      pathFmt: "/production/wake",
      pathArgs: [],
      body: null,
      successCode: 202,
      errorCodes: { 401: "ErrorResponse" },
    });
  }

  /** Wake a regional environment of a model. */
  async wakeRegional(): Promise<void> {
    await this._doNoResponse({
      method: "POST",
      pathFmt: "/wake",
      pathArgs: [],
      body: null,
      successCode: 202,
      errorCodes: { 401: "ErrorResponse" },
    });
  }

  private async _do(request: ApiRequest): Promise<Response> {
    const path = request.pathFmt.replace(
      /\{\}/g,
      (() => {
        let i = 0;
        return () => encodeURIComponent(request.pathArgs[i++]);
      })(),
    );
    const init: RequestInit = {
      method: request.method,
      headers: { ...this.headers },
    };
    if (request.body !== null) {
      (init.headers as Record<string, string>)["Content-Type"] = "application/json";
      init.body = JSON.stringify(request.body);
    }
    const response = await this.fetchImpl(`${this.baseUrl}${path}`, init);
    if (response.status !== request.successCode) {
      if (request.errorCodes?.[response.status]) {
        const ErrorClass = ERROR_TYPES[request.errorCodes[response.status]];
        if (ErrorClass) {
          try {
            const data = await response.json();
            throw new ErrorClass(response.status, data);
          } catch (e) {
            if (Object.values(ERROR_TYPES).some((cls) => e instanceof cls)) throw e;
          }
        }
      }
      throw new ResponseError(response.status, await response.text());
    }
    return response;
  }

  // TODO(https://github.com/basetenlabs/baseten-js/issues/2): support non-JSON response content types
  private async _doJson<T>(request: ApiRequest): Promise<T> {
    const response = await this._do(request);
    const contentType = response.headers.get("content-type") || "";
    if (!contentType.includes("application/json")) {
      throw new ResponseError(
        response.status,
        `non-JSON response content type not currently supported, got ${contentType}`,
      );
    }
    return (await response.json()) as T;
  }

  private async _doNoResponse(request: ApiRequest): Promise<void> {
    await this._do(request);
  }
}
