/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type components = {
  schemas: {
    AsyncPredictRequest: {
      /** @description JSON-serializable model input. */
      model_input: Record<string, unknown>;
      /**
       * Format: uri
       * @description HTTPS URL to receive the prediction result via webhook. Both HTTP/2 and HTTP/1.1 are supported. If omitted, the model must save outputs so they can be accessed later.
       */
      webhook_endpoint?: string;
      /**
       * @description Priority of the request. Lower values are higher priority.
       * @default 0
       */
      priority: number;
      /**
       * @description Maximum time in seconds a request will spend in the queue before expiring. Must be between 10 seconds and 72 hours.
       * @default 600
       */
      max_time_in_queue_seconds: number;
      inference_retry_config?: components["schemas"]["InferenceRetryConfig"];
    };
    /** @description Exponential backoff parameters for retrying predict requests. */
    InferenceRetryConfig: {
      /**
       * @description Number of predict request attempts.
       * @default 3
       */
      max_attempts: number;
      /**
       * @description Minimum time between retries in milliseconds.
       * @default 1000
       */
      initial_delay_ms: number;
      /**
       * @description Maximum time between retries in milliseconds.
       * @default 5000
       */
      max_delay_ms: number;
    };
    AsyncRequestStatusResponse: {
      /** @description The ID of the async request. */
      request_id: string;
      /** @description The ID of the model that executed the request. Present for model requests. */
      model_id?: string;
      /** @description The ID of the chain that executed the request. Present for chain requests. */
      chain_id?: string;
      /** @description The ID of the deployment that executed the request. */
      deployment_id: string;
      /**
       * @description The status of the async request.
       * @enum {string}
       */
      status:
        | "QUEUED"
        | "IN_PROGRESS"
        | "SUCCEEDED"
        | "FAILED"
        | "EXPIRED"
        | "CANCELED"
        | "WEBHOOK_FAILED";
      /**
       * @description The status of sending the prediction result to the provided webhook.
       * @enum {string}
       */
      webhook_status: "PENDING" | "SUCCEEDED" | "FAILED" | "CANCELED" | "NO_WEBHOOK_PROVIDED";
      /** @description The time in UTC at which the async request was created. */
      created_at: string;
      /** @description The time in UTC at which the async request's status was last updated. */
      status_at: string;
      /**
       * @description Errors that occurred while processing the async request. Empty if no errors occurred.
       * @default []
       */
      errors: components["schemas"]["AsyncRequestError"][];
    };
    AsyncRequestError: {
      /**
       * @description The type of error that occurred.
       * @enum {string}
       */
      code:
        | "MODEL_PREDICT_ERROR"
        | "MODEL_PREDICT_TIMEOUT"
        | "MODEL_NOT_READY"
        | "MODEL_DOES_NOT_EXIST"
        | "MODEL_UNAVAILABLE"
        | "MODEL_INVALID_INPUT"
        | "ASYNC_REQUEST_NOT_SUPPORTED"
        | "INTERNAL_SERVER_ERROR";
      /** @description Details of the error. */
      message: string;
    };
    ErrorResponse: {
      /** @description Human-readable error message. */
      error?: string;
      /**
       * @description Machine-readable error code.
       * @enum {string}
       */
      error_code?:
        | "timeout"
        | "client_error"
        | "model_unavailable"
        | "model_not_ready"
        | "model_does_not_exist"
        | "rate_limited"
        | "payload_too_large"
        | "unauthorized"
        | "application_error"
        | "internal_baseten_error";
      /** @description Additional error details, if available. */
      detail?: string;
    };
    /** @description JSON-serializable output. The shape is defined by the model. */
    PredictOutput: Record<string, unknown>;
    /** @description JSON-serializable output. The shape is defined by the chain. */
    RunRemoteOutput: Record<string, unknown>;
    AsyncPredictOutput: {
      /** @description The ID of the async request. */
      request_id: string;
    };
    AsyncRunRemoteOutput: {
      /** @description The ID of the async request. */
      request_id: string;
    };
    CancelAsyncRequestOutput: {
      /** @description The ID of the async request. */
      request_id: string;
      /** @description Whether the request was canceled. */
      canceled: boolean;
      /** @description Additional details about whether the request was canceled. */
      message: string;
    };
    GetAsyncQueueStatusOutput: {
      /** @description The ID of the model. */
      model_id: string;
      /** @description The ID of the deployment. */
      deployment_id: string;
      /** @description Number of requests with QUEUED status awaiting processing. */
      num_queued_requests: number;
      /** @description Number of requests currently being processed by the model. */
      num_in_progress_requests: number;
    };
    /** @description JSON-serializable model input. The shape is defined by the model's `predict` function. */
    PredictInput: Record<string, unknown>;
    /** @description JSON input matching the chain's `run_remote` method signature. */
    RunRemoteInput: Record<string, unknown>;
    /** @description JSON input matching the chain's `run_remote` method signature. */
    AsyncRunRemoteInput: Record<string, unknown>;
  };
  responses: {
    /** @description Successful synchronous prediction. */
    PredictOutput: {
      headers: {
        "X-BASETEN-REQUEST-ID": components["headers"]["X-BASETEN-REQUEST-ID"];
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["PredictOutput"];
        "application/octet-stream": string;
      };
    };
    /** @description Successful synchronous chain execution. */
    RunRemoteOutput: {
      headers: {
        "X-BASETEN-REQUEST-ID": components["headers"]["X-BASETEN-REQUEST-ID"];
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["RunRemoteOutput"];
      };
    };
    /** @description Async predict request enqueued. */
    AsyncPredictOutput: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["AsyncPredictOutput"];
      };
    };
    /** @description Async run remote request enqueued. */
    AsyncRunRemoteOutput: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["AsyncRunRemoteOutput"];
      };
    };
    /** @description Current status of an async request. */
    GetAsyncRequestStatusOutput: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["AsyncRequestStatusResponse"];
      };
    };
    /** @description Result of an async request cancellation. */
    CancelAsyncRequestOutput: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["CancelAsyncRequestOutput"];
      };
    };
    /** @description Async queue status for a deployment. */
    GetAsyncQueueStatusOutput: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["GetAsyncQueueStatusOutput"];
      };
    };
    /** @description Error response. */
    Error: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["ErrorResponse"];
      };
    };
  };
  parameters: {
    /** @description The name of the environment (e.g. `production`, `staging`). */
    env_name: string;
    /** @description The alphanumeric ID of the deployment. */
    deployment_id: string;
    /** @description The ID of the async request. */
    request_id: string;
  };
  requestBodies: {
    PredictInput: {
      content: {
        "application/json": components["schemas"]["PredictInput"];
        "application/octet-stream": string;
        "multipart/form-data": Record<string, unknown>;
      };
    };
    RunRemoteInput: {
      content: {
        "application/json": components["schemas"]["RunRemoteInput"];
      };
    };
    /** @description There is a 256 KiB size limit on async predict request payloads. */
    AsyncPredictInput: {
      content: {
        "application/json": components["schemas"]["AsyncPredictRequest"];
      };
    };
    AsyncRunRemoteInput: {
      content: {
        "application/json": components["schemas"]["AsyncRunRemoteInput"];
      };
    };
  };
  headers: {
    /** @description Unique identifier for the request. */
    "X-BASETEN-REQUEST-ID": string;
  };
  pathItems: never;
};
export type AsyncPredictRequest = components["schemas"]["AsyncPredictRequest"];
export type InferenceRetryConfig = components["schemas"]["InferenceRetryConfig"];
export type AsyncRequestStatusResponse = components["schemas"]["AsyncRequestStatusResponse"];
export type AsyncRequestError = components["schemas"]["AsyncRequestError"];
export type ErrorResponse = components["schemas"]["ErrorResponse"];
export type PredictOutput = components["schemas"]["PredictOutput"];
export type RunRemoteOutput = components["schemas"]["RunRemoteOutput"];
export type AsyncPredictOutput = components["schemas"]["AsyncPredictOutput"];
export type AsyncRunRemoteOutput = components["schemas"]["AsyncRunRemoteOutput"];
export type CancelAsyncRequestOutput = components["schemas"]["CancelAsyncRequestOutput"];
export type GetAsyncQueueStatusOutput = components["schemas"]["GetAsyncQueueStatusOutput"];
export type PredictInput = components["schemas"]["PredictInput"];
export type RunRemoteInput = components["schemas"]["RunRemoteInput"];
export type AsyncRunRemoteInput = components["schemas"]["AsyncRunRemoteInput"];
