// Code generated by apigen/clientgen. DO NOT EDIT.

import type {
  ActivateResponse,
  ApiKey,
  ApiKeyTombstone,
  ApiKeys,
  CancelPromotionResponse,
  Chain,
  ChainDeployment,
  ChainDeploymentTombstone,
  ChainDeployments,
  ChainEnvironment,
  ChainTombstone,
  Chains,
  CreateApiKeyRequest,
  CreateChainEnvironmentRequest,
  CreateEnvironmentRequest,
  CreateLibraryListingRequest,
  CreateLibraryListingVersionRequest,
  CreateLlmModelRequest,
  CreateLlmModelVersionRequest,
  CreateModelWeightSnapshotRequest,
  CreateTrainingJobRequest,
  CreateTrainingJobResponse,
  DeactivateResponse,
  Deployment,
  DeploymentTombstone,
  Deployments,
  DownloadTrainingJobResponse,
  Environment,
  Environments,
  GetAuthCodesResponse,
  GetBlobCredentialsResponse,
  GetCacheSummaryResponse,
  GetDeploymentLogsRequest,
  GetLogsResponse,
  GetTrainingJobCheckpointFilesResponse,
  GetTrainingJobCheckpointsResponse,
  GetTrainingJobLogsRequest,
  GetTrainingJobMetricsRequest,
  GetTrainingJobMetricsResponse,
  GetTrainingJobResponse,
  GetTrainingProjectResponse,
  InstanceTypePrices,
  InstanceTypes,
  LibraryListing,
  LibraryListingTombstone,
  LibraryListingVersion,
  LibraryListingVersionTombstone,
  LibraryListingVersions,
  LibraryListings,
  ListTrainingJobsResponse,
  ListTrainingProjectsResponse,
  LlmModel,
  LlmModelVersion,
  Model,
  ModelTombstone,
  ModelWeightSnapshot,
  Models,
  PatchInteractiveSessionRequest,
  PatchInteractiveSessionResponse,
  PromoteRequest,
  PromoteToChainEnvironmentRequest,
  PromoteToEnvironmentRequest,
  RecreateTrainingJobResponse,
  RetryDeploymentResponse,
  SearchTrainingJobsRequest,
  SearchTrainingJobsResponse,
  Secret,
  Secrets,
  SignalPromotionResponse,
  StopTrainingJobRequest,
  StopTrainingJobResponse,
  Teams,
  TerminateReplicaResponse,
  TrainingJobTombstone,
  TrainingProjectTombstone,
  UpdateAutoscalingSettings,
  UpdateAutoscalingSettingsResponse,
  UpdateChainEnvironmentRequest,
  UpdateChainEnvironmentResponse,
  UpdateChainletEnvironmentAutoscalingSettingsRequest,
  UpdateChainletEnvironmentInstanceTypeRequest,
  UpdateChainletEnvironmentInstanceTypeResponse,
  UpdateEnvironmentRequest,
  UpdateLibraryListingRequest,
  UpdateLibraryListingVersionRequest,
  UpsertSecretRequest,
  UpsertTrainingProjectRequest,
  UpsertTrainingProjectResponse,
  UsageSummary,
} from "./models.gen";

export class ResponseError extends Error {
  constructor(
    public readonly statusCode: number,
    public readonly body: string,
  ) {
    super(`baseten API error (HTTP ${statusCode}): ${body}`);
  }
}

interface ApiRequest {
  method: string;
  pathFmt: string;
  pathArgs: string[];
  body: unknown;
  successCode: number;
  errorCodes: Record<number, string> | null;
}

export class ApiClient {
  /**
   * Generated HTTP client for the Baseten API.
   *
   * Methods on this client are generated from the OpenAPI specification
   * and are NOT covered by any stability or compatibility guarantees.
   * They may change without notice between versions.
   */
  private readonly baseUrl: string;
  private readonly headers: Record<string, string>;
  private readonly fetchImpl: typeof fetch;

  constructor(options: { baseUrl: string; headers: Record<string, string>; fetch?: typeof fetch }) {
    this.baseUrl = options.baseUrl;
    this.headers = options.headers;
    this.fetchImpl = options.fetch ?? globalThis.fetch;
  }

  /** Deletes an API key by prefix */
  async deleteApiKeys(params: { api_key_prefix: string }): Promise<ApiKeyTombstone> {
    return this._doJson<ApiKeyTombstone>({
      method: "DELETE",
      pathFmt: "/v1/api_keys/{}",
      pathArgs: [params.api_key_prefix],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Deletes a chain by ID */
  async deleteChains(params: { chain_id: string }): Promise<ChainTombstone> {
    return this._doJson<ChainTombstone>({
      method: "DELETE",
      pathFmt: "/v1/chains/{}",
      pathArgs: [params.chain_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Deletes a chain deployment by ID */
  async deleteChainsDeployments(params: {
    chain_id: string;
    chain_deployment_id: string;
  }): Promise<ChainDeploymentTombstone> {
    return this._doJson<ChainDeploymentTombstone>({
      method: "DELETE",
      pathFmt: "/v1/chains/{}/deployments/{}",
      pathArgs: [params.chain_id, params.chain_deployment_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Deletes a library listing */
  async deleteLibraryListings(params: {
    user_defined_listing_id: string;
  }): Promise<LibraryListingTombstone> {
    return this._doJson<LibraryListingTombstone>({
      method: "DELETE",
      pathFmt: "/v1/library_listings/{}",
      pathArgs: [params.user_defined_listing_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Deletes a library listing version */
  async deleteLibraryListingsVersions(params: {
    user_defined_listing_id: string;
    version_tag: string;
  }): Promise<LibraryListingVersionTombstone> {
    return this._doJson<LibraryListingVersionTombstone>({
      method: "DELETE",
      pathFmt: "/v1/library_listings/{}/versions/{}",
      pathArgs: [params.user_defined_listing_id, params.version_tag],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Deletes a model by ID */
  async deleteModels(params: { model_id: string }): Promise<ModelTombstone> {
    return this._doJson<ModelTombstone>({
      method: "DELETE",
      pathFmt: "/v1/models/{}",
      pathArgs: [params.model_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Deletes a model's deployment by ID */
  async deleteModelsDeployments(params: {
    model_id: string;
    deployment_id: string;
  }): Promise<DeploymentTombstone> {
    return this._doJson<DeploymentTombstone>({
      method: "DELETE",
      pathFmt: "/v1/models/{}/deployments/{}",
      pathArgs: [params.model_id, params.deployment_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Terminates a replica in a deployment */
  async deleteModelsDeploymentsReplicas(params: {
    model_id: string;
    deployment_id: string;
    replica_id: string;
  }): Promise<TerminateReplicaResponse> {
    return this._doJson<TerminateReplicaResponse>({
      method: "DELETE",
      pathFmt: "/v1/models/{}/deployments/{}/replicas/{}",
      pathArgs: [params.model_id, params.deployment_id, params.replica_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Delete a training project. */
  async deleteTrainingProjects(params: {
    training_project_id: string;
  }): Promise<TrainingProjectTombstone> {
    return this._doJson<TrainingProjectTombstone>({
      method: "DELETE",
      pathFmt: "/v1/training_projects/{}",
      pathArgs: [params.training_project_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Delete a training job. */
  async deleteTrainingProjectsJobs(params: {
    training_project_id: string;
    training_job_id: string;
  }): Promise<TrainingJobTombstone> {
    return this._doJson<TrainingJobTombstone>({
      method: "DELETE",
      pathFmt: "/v1/training_projects/{}/jobs/{}",
      pathArgs: [params.training_project_id, params.training_job_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Lists the user's API keys */
  async getApiKeys(): Promise<ApiKeys> {
    return this._doJson<ApiKeys>({
      method: "GET",
      pathFmt: "/v1/api_keys",
      pathArgs: [],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets billing usage summary for a date range */
  async getBillingUsageSummary(): Promise<UsageSummary> {
    return this._doJson<UsageSummary>({
      method: "GET",
      pathFmt: "/v1/billing/usage_summary",
      pathArgs: [],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get blob credentials for models. */
  async getBlobsCredentialsModel(): Promise<GetBlobCredentialsResponse> {
    return this._doJson<GetBlobCredentialsResponse>({
      method: "GET",
      pathFmt: "/v1/blobs/credentials/model",
      pathArgs: [],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get blob credentials for training. */
  async getBlobsCredentialsTrain(): Promise<GetBlobCredentialsResponse> {
    return this._doJson<GetBlobCredentialsResponse>({
      method: "GET",
      pathFmt: "/v1/blobs/credentials/train",
      pathArgs: [],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets all chains */
  async getChains(): Promise<Chains> {
    return this._doJson<Chains>({
      method: "GET",
      pathFmt: "/v1/chains",
      pathArgs: [],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets a chain by ID */
  async getChainsChainId(params: { chain_id: string }): Promise<Chain> {
    return this._doJson<Chain>({
      method: "GET",
      pathFmt: "/v1/chains/{}",
      pathArgs: [params.chain_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets all chain deployments */
  async getChainsDeployments(params: { chain_id: string }): Promise<ChainDeployments> {
    return this._doJson<ChainDeployments>({
      method: "GET",
      pathFmt: "/v1/chains/{}/deployments",
      pathArgs: [params.chain_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets a chain deployment by ID */
  async getChainsDeploymentsChainDeploymentId(params: {
    chain_id: string;
    chain_deployment_id: string;
  }): Promise<ChainDeployment> {
    return this._doJson<ChainDeployment>({
      method: "GET",
      pathFmt: "/v1/chains/{}/deployments/{}",
      pathArgs: [params.chain_id, params.chain_deployment_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get all chain environments */
  async getChainsEnvironments(params: { chain_id: string }): Promise<Environments> {
    return this._doJson<Environments>({
      method: "GET",
      pathFmt: "/v1/chains/{}/environments",
      pathArgs: [params.chain_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get a chain environment's details */
  async getChainsEnvironmentsEnvName(params: {
    chain_id: string;
    env_name: string;
  }): Promise<ChainEnvironment> {
    return this._doJson<ChainEnvironment>({
      method: "GET",
      pathFmt: "/v1/chains/{}/environments/{}",
      pathArgs: [params.chain_id, params.env_name],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets prices for available instance types. */
  async getInstanceTypePrices(): Promise<InstanceTypePrices> {
    return this._doJson<InstanceTypePrices>({
      method: "GET",
      pathFmt: "/v1/instance_type_prices",
      pathArgs: [],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets all available instance types */
  async getInstanceTypes(): Promise<InstanceTypes> {
    return this._doJson<InstanceTypes>({
      method: "GET",
      pathFmt: "/v1/instance_types",
      pathArgs: [],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets all library listings */
  async getLibraryListings(): Promise<LibraryListings> {
    return this._doJson<LibraryListings>({
      method: "GET",
      pathFmt: "/v1/library_listings",
      pathArgs: [],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets a library listing */
  async getLibraryListingsUserDefinedListingId(params: {
    user_defined_listing_id: string;
  }): Promise<LibraryListing> {
    return this._doJson<LibraryListing>({
      method: "GET",
      pathFmt: "/v1/library_listings/{}",
      pathArgs: [params.user_defined_listing_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets all versions for a library listing */
  async getLibraryListingsVersions(params: {
    user_defined_listing_id: string;
  }): Promise<LibraryListingVersions> {
    return this._doJson<LibraryListingVersions>({
      method: "GET",
      pathFmt: "/v1/library_listings/{}/versions",
      pathArgs: [params.user_defined_listing_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets a library listing version */
  async getLibraryListingsVersionsVersionTag(params: {
    user_defined_listing_id: string;
    version_tag: string;
  }): Promise<LibraryListingVersion> {
    return this._doJson<LibraryListingVersion>({
      method: "GET",
      pathFmt: "/v1/library_listings/{}/versions/{}",
      pathArgs: [params.user_defined_listing_id, params.version_tag],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get the latest model weight snapshot */
  async getModelApisSnapshots(): Promise<ModelWeightSnapshot> {
    return this._doJson<ModelWeightSnapshot>({
      method: "GET",
      pathFmt: "/v1/model_apis/snapshots",
      pathArgs: [],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get the latest model weight snapshot */
  async getModelApisSnapshotsModelId(params: { model_id: string }): Promise<ModelWeightSnapshot> {
    return this._doJson<ModelWeightSnapshot>({
      method: "GET",
      pathFmt: "/v1/model_apis/snapshots/{}",
      pathArgs: [params.model_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets all models */
  async getModels(): Promise<Models> {
    return this._doJson<Models>({
      method: "GET",
      pathFmt: "/v1/models",
      pathArgs: [],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets all deployments of a model */
  async getModelsDeployments(params: { model_id: string }): Promise<Deployments> {
    return this._doJson<Deployments>({
      method: "GET",
      pathFmt: "/v1/models/{}/deployments",
      pathArgs: [params.model_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets a model's deployment by ID */
  async getModelsDeploymentsDeploymentId(params: {
    model_id: string;
    deployment_id: string;
  }): Promise<Deployment> {
    return this._doJson<Deployment>({
      method: "GET",
      pathFmt: "/v1/models/{}/deployments/{}",
      pathArgs: [params.model_id, params.deployment_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets a model's development deployment */
  async getModelsDeploymentsDevelopment(params: { model_id: string }): Promise<Deployment> {
    return this._doJson<Deployment>({
      method: "GET",
      pathFmt: "/v1/models/{}/deployments/development",
      pathArgs: [params.model_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets a model's production deployment */
  async getModelsDeploymentsProduction(params: { model_id: string }): Promise<Deployment> {
    return this._doJson<Deployment>({
      method: "GET",
      pathFmt: "/v1/models/{}/deployments/production",
      pathArgs: [params.model_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get all environments */
  async getModelsEnvironments(params: { model_id: string }): Promise<Environments> {
    return this._doJson<Environments>({
      method: "GET",
      pathFmt: "/v1/models/{}/environments",
      pathArgs: [params.model_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get an environment's details */
  async getModelsEnvironmentsEnvName(params: {
    model_id: string;
    env_name: string;
  }): Promise<Environment> {
    return this._doJson<Environment>({
      method: "GET",
      pathFmt: "/v1/models/{}/environments/{}",
      pathArgs: [params.model_id, params.env_name],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets a model by ID */
  async getModelsModelId(params: { model_id: string }): Promise<Model> {
    return this._doJson<Model>({
      method: "GET",
      pathFmt: "/v1/models/{}",
      pathArgs: [params.model_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets all secrets */
  async getSecrets(): Promise<Secrets> {
    return this._doJson<Secrets>({
      method: "GET",
      pathFmt: "/v1/secrets",
      pathArgs: [],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Lists all teams */
  async getTeams(): Promise<Teams> {
    return this._doJson<Teams>({
      method: "GET",
      pathFmt: "/v1/teams",
      pathArgs: [],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets all secrets for a team */
  async getTeamsSecrets(params: { team_id: string }): Promise<Secrets> {
    return this._doJson<Secrets>({
      method: "GET",
      pathFmt: "/v1/teams/{}/secrets",
      pathArgs: [params.team_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** List training projects. */
  async getTrainingProjects(): Promise<ListTrainingProjectsResponse> {
    return this._doJson<ListTrainingProjectsResponse>({
      method: "GET",
      pathFmt: "/v1/training_projects",
      pathArgs: [],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get training project cache summary. */
  async getTrainingProjectsCacheSummary(params: {
    training_project_id: string;
  }): Promise<GetCacheSummaryResponse> {
    return this._doJson<GetCacheSummaryResponse>({
      method: "GET",
      pathFmt: "/v1/training_projects/{}/cache/summary",
      pathArgs: [params.training_project_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** List training jobs. */
  async getTrainingProjectsJobs(params: {
    training_project_id: string;
  }): Promise<ListTrainingJobsResponse> {
    return this._doJson<ListTrainingJobsResponse>({
      method: "GET",
      pathFmt: "/v1/training_projects/{}/jobs",
      pathArgs: [params.training_project_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get auth codes for a training job. */
  async getTrainingProjectsJobsAuthCodes(params: {
    training_project_id: string;
    training_job_id: string;
  }): Promise<GetAuthCodesResponse> {
    return this._doJson<GetAuthCodesResponse>({
      method: "GET",
      pathFmt: "/v1/training_projects/{}/jobs/{}/auth_codes",
      pathArgs: [params.training_project_id, params.training_job_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get training job checkpoint files. */
  async getTrainingProjectsJobsCheckpointFiles(params: {
    training_project_id: string;
    training_job_id: string;
  }): Promise<GetTrainingJobCheckpointFilesResponse> {
    return this._doJson<GetTrainingJobCheckpointFilesResponse>({
      method: "GET",
      pathFmt: "/v1/training_projects/{}/jobs/{}/checkpoint_files",
      pathArgs: [params.training_project_id, params.training_job_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get training job checkpoints. */
  async getTrainingProjectsJobsCheckpoints(params: {
    training_project_id: string;
    training_job_id: string;
  }): Promise<GetTrainingJobCheckpointsResponse> {
    return this._doJson<GetTrainingJobCheckpointsResponse>({
      method: "GET",
      pathFmt: "/v1/training_projects/{}/jobs/{}/checkpoints",
      pathArgs: [params.training_project_id, params.training_job_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get the uploaded training job as a S3 Artifact */
  async getTrainingProjectsJobsDownload(params: {
    training_project_id: string;
    training_job_id: string;
  }): Promise<DownloadTrainingJobResponse> {
    return this._doJson<DownloadTrainingJobResponse>({
      method: "GET",
      pathFmt: "/v1/training_projects/{}/jobs/{}/download",
      pathArgs: [params.training_project_id, params.training_job_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get a training job. */
  async getTrainingProjectsJobsTrainingJobId(params: {
    training_project_id: string;
    training_job_id: string;
  }): Promise<GetTrainingJobResponse> {
    return this._doJson<GetTrainingJobResponse>({
      method: "GET",
      pathFmt: "/v1/training_projects/{}/jobs/{}",
      pathArgs: [params.training_project_id, params.training_job_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get a training project. */
  async getTrainingProjectsTrainingProjectId(params: {
    training_project_id: string;
  }): Promise<GetTrainingProjectResponse> {
    return this._doJson<GetTrainingProjectResponse>({
      method: "GET",
      pathFmt: "/v1/training_projects/{}",
      pathArgs: [params.training_project_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Update a chain environment's settings */
  async patchChainsEnvironments(params: {
    chain_id: string;
    env_name: string;
    body: UpdateChainEnvironmentRequest;
  }): Promise<UpdateChainEnvironmentResponse> {
    return this._doJson<UpdateChainEnvironmentResponse>({
      method: "PATCH",
      pathFmt: "/v1/chains/{}/environments/{}",
      pathArgs: [params.chain_id, params.env_name],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Update a chainlet environment's autoscaling settings */
  async patchChainsEnvironmentsChainletSettingsAutoscalingSettings(params: {
    chain_id: string;
    env_name: string;
    body: UpdateChainletEnvironmentAutoscalingSettingsRequest;
  }): Promise<UpdateAutoscalingSettingsResponse> {
    return this._doJson<UpdateAutoscalingSettingsResponse>({
      method: "PATCH",
      pathFmt: "/v1/chains/{}/environments/{}/chainlet_settings/autoscaling_settings",
      pathArgs: [params.chain_id, params.env_name],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Updates a library listing */
  async patchLibraryListings(params: {
    user_defined_listing_id: string;
    body: UpdateLibraryListingRequest;
  }): Promise<LibraryListing> {
    return this._doJson<LibraryListing>({
      method: "PATCH",
      pathFmt: "/v1/library_listings/{}",
      pathArgs: [params.user_defined_listing_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Updates a library listing version */
  async patchLibraryListingsVersions(params: {
    user_defined_listing_id: string;
    version_tag: string;
    body: UpdateLibraryListingVersionRequest;
  }): Promise<LibraryListingVersion> {
    return this._doJson<LibraryListingVersion>({
      method: "PATCH",
      pathFmt: "/v1/library_listings/{}/versions/{}",
      pathArgs: [params.user_defined_listing_id, params.version_tag],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Updates a deployment's autoscaling settings */
  async patchModelsDeploymentsAutoscalingSettings(params: {
    model_id: string;
    deployment_id: string;
    body: UpdateAutoscalingSettings;
  }): Promise<UpdateAutoscalingSettingsResponse> {
    return this._doJson<UpdateAutoscalingSettingsResponse>({
      method: "PATCH",
      pathFmt: "/v1/models/{}/deployments/{}/autoscaling_settings",
      pathArgs: [params.model_id, params.deployment_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Updates a development deployment's autoscaling settings */
  async patchModelsDeploymentsDevelopmentAutoscalingSettings(params: {
    model_id: string;
    body: UpdateAutoscalingSettings;
  }): Promise<UpdateAutoscalingSettingsResponse> {
    return this._doJson<UpdateAutoscalingSettingsResponse>({
      method: "PATCH",
      pathFmt: "/v1/models/{}/deployments/development/autoscaling_settings",
      pathArgs: [params.model_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Updates a production deployment's autoscaling settings */
  async patchModelsDeploymentsProductionAutoscalingSettings(params: {
    model_id: string;
    body: UpdateAutoscalingSettings;
  }): Promise<UpdateAutoscalingSettingsResponse> {
    return this._doJson<UpdateAutoscalingSettingsResponse>({
      method: "PATCH",
      pathFmt: "/v1/models/{}/deployments/production/autoscaling_settings",
      pathArgs: [params.model_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Update an environment's settings */
  async patchModelsEnvironments(params: {
    model_id: string;
    env_name: string;
    body: UpdateEnvironmentRequest;
  }): Promise<UpdateAutoscalingSettingsResponse> {
    return this._doJson<UpdateAutoscalingSettingsResponse>({
      method: "PATCH",
      pathFmt: "/v1/models/{}/environments/{}",
      pathArgs: [params.model_id, params.env_name],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Patch an interactive session. */
  async patchTrainingProjectsJobsInteractiveSessions(params: {
    training_project_id: string;
    training_job_id: string;
    session_id: string;
    body: PatchInteractiveSessionRequest;
  }): Promise<PatchInteractiveSessionResponse> {
    return this._doJson<PatchInteractiveSessionResponse>({
      method: "PATCH",
      pathFmt: "/v1/training_projects/{}/jobs/{}/interactive_sessions/{}",
      pathArgs: [params.training_project_id, params.training_job_id, params.session_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Creates an API key */
  async postApiKeys(params: { body: CreateApiKeyRequest }): Promise<ApiKey> {
    return this._doJson<ApiKey>({
      method: "POST",
      pathFmt: "/v1/api_keys",
      pathArgs: [],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Deactivates a chain deployment */
  async postChainsDeploymentsDeactivate(params: {
    chain_id: string;
    chain_deployment_id: string;
  }): Promise<DeactivateResponse> {
    return this._doJson<DeactivateResponse>({
      method: "POST",
      pathFmt: "/v1/chains/{}/deployments/{}/deactivate",
      pathArgs: [params.chain_id, params.chain_deployment_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Create a chain environment */
  async postChainsEnvironments(params: {
    chain_id: string;
    body: CreateChainEnvironmentRequest;
  }): Promise<ChainEnvironment> {
    return this._doJson<ChainEnvironment>({
      method: "POST",
      pathFmt: "/v1/chains/{}/environments",
      pathArgs: [params.chain_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Update a chainlet environment's instance type settings. */
  async postChainsEnvironmentsChainletSettingsInstanceTypesUpdate(params: {
    chain_id: string;
    env_name: string;
    body: UpdateChainletEnvironmentInstanceTypeRequest;
  }): Promise<UpdateChainletEnvironmentInstanceTypeResponse> {
    return this._doJson<UpdateChainletEnvironmentInstanceTypeResponse>({
      method: "POST",
      pathFmt: "/v1/chains/{}/environments/{}/chainlet_settings/instance_types/update",
      pathArgs: [params.chain_id, params.env_name],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Promotes a chain deployment to an environment */
  async postChainsEnvironmentsPromote(params: {
    chain_id: string;
    env_name: string;
    body: PromoteToChainEnvironmentRequest;
  }): Promise<ChainDeployment> {
    return this._doJson<ChainDeployment>({
      method: "POST",
      pathFmt: "/v1/chains/{}/environments/{}/promote",
      pathArgs: [params.chain_id, params.env_name],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Creates a new library listing */
  async postLibraryListings(params: {
    body: CreateLibraryListingRequest;
  }): Promise<LibraryListing> {
    return this._doJson<LibraryListing>({
      method: "POST",
      pathFmt: "/v1/library_listings",
      pathArgs: [],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Creates a new library listing version */
  async postLibraryListingsVersions(params: {
    user_defined_listing_id: string;
    body: CreateLibraryListingVersionRequest;
  }): Promise<LibraryListingVersion> {
    return this._doJson<LibraryListingVersion>({
      method: "POST",
      pathFmt: "/v1/library_listings/{}/versions",
      pathArgs: [params.user_defined_listing_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Creates a new BIS LLM deployment */
  async postLlmModels(params: { body: CreateLlmModelRequest }): Promise<LlmModel> {
    return this._doJson<LlmModel>({
      method: "POST",
      pathFmt: "/v1/llm_models",
      pathArgs: [],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Creates a new BIS LLM deployment version */
  async postLlmModelsDeployments(params: {
    model_id: string;
    body: CreateLlmModelVersionRequest;
  }): Promise<LlmModelVersion> {
    return this._doJson<LlmModelVersion>({
      method: "POST",
      pathFmt: "/v1/llm_models/{}/deployments",
      pathArgs: [params.model_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Create a model weight snapshot */
  async postModelApisSnapshots(params: {
    body: CreateModelWeightSnapshotRequest;
  }): Promise<ModelWeightSnapshot> {
    return this._doJson<ModelWeightSnapshot>({
      method: "POST",
      pathFmt: "/v1/model_apis/snapshots",
      pathArgs: [],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Create a model weight snapshot */
  async postModelApisSnapshotsModelId(params: {
    model_id: string;
    body: CreateModelWeightSnapshotRequest;
  }): Promise<ModelWeightSnapshot> {
    return this._doJson<ModelWeightSnapshot>({
      method: "POST",
      pathFmt: "/v1/model_apis/snapshots/{}",
      pathArgs: [params.model_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Activates a deployment */
  async postModelsDeploymentsActivate(params: {
    model_id: string;
    deployment_id: string;
  }): Promise<ActivateResponse> {
    return this._doJson<ActivateResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/deployments/{}/activate",
      pathArgs: [params.model_id, params.deployment_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Deactivates a deployment */
  async postModelsDeploymentsDeactivate(params: {
    model_id: string;
    deployment_id: string;
  }): Promise<DeactivateResponse> {
    return this._doJson<DeactivateResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/deployments/{}/deactivate",
      pathArgs: [params.model_id, params.deployment_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Activates a development deployment */
  async postModelsDeploymentsDevelopmentActivate(params: {
    model_id: string;
  }): Promise<ActivateResponse> {
    return this._doJson<ActivateResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/deployments/development/activate",
      pathArgs: [params.model_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Deactivates a development deployment */
  async postModelsDeploymentsDevelopmentDeactivate(params: {
    model_id: string;
  }): Promise<DeactivateResponse> {
    return this._doJson<DeactivateResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/deployments/development/deactivate",
      pathArgs: [params.model_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Promotes a development deployment to production */
  async postModelsDeploymentsDevelopmentPromote(params: {
    model_id: string;
    body: PromoteRequest;
  }): Promise<Deployment> {
    return this._doJson<Deployment>({
      method: "POST",
      pathFmt: "/v1/models/{}/deployments/development/promote",
      pathArgs: [params.model_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Retries a failed development deployment */
  async postModelsDeploymentsDevelopmentRetry(params: {
    model_id: string;
  }): Promise<RetryDeploymentResponse> {
    return this._doJson<RetryDeploymentResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/deployments/development/retry",
      pathArgs: [params.model_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Gets the logs for a model deployment. */
  async postModelsDeploymentsLogs(params: {
    model_id: string;
    deployment_id: string;
    body: GetDeploymentLogsRequest;
  }): Promise<GetLogsResponse> {
    return this._doJson<GetLogsResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/deployments/{}/logs",
      pathArgs: [params.model_id, params.deployment_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Activates a production deployment */
  async postModelsDeploymentsProductionActivate(params: {
    model_id: string;
  }): Promise<ActivateResponse> {
    return this._doJson<ActivateResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/deployments/production/activate",
      pathArgs: [params.model_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Deactivates a production deployment */
  async postModelsDeploymentsProductionDeactivate(params: {
    model_id: string;
  }): Promise<DeactivateResponse> {
    return this._doJson<DeactivateResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/deployments/production/deactivate",
      pathArgs: [params.model_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Retries a failed production deployment */
  async postModelsDeploymentsProductionRetry(params: {
    model_id: string;
  }): Promise<RetryDeploymentResponse> {
    return this._doJson<RetryDeploymentResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/deployments/production/retry",
      pathArgs: [params.model_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Promotes a deployment to production */
  async postModelsDeploymentsPromote(params: {
    model_id: string;
    deployment_id: string;
    body: PromoteRequest;
  }): Promise<Deployment> {
    return this._doJson<Deployment>({
      method: "POST",
      pathFmt: "/v1/models/{}/deployments/{}/promote",
      pathArgs: [params.model_id, params.deployment_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Retries a failed deployment */
  async postModelsDeploymentsRetry(params: {
    model_id: string;
    deployment_id: string;
  }): Promise<RetryDeploymentResponse> {
    return this._doJson<RetryDeploymentResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/deployments/{}/retry",
      pathArgs: [params.model_id, params.deployment_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Create an environment */
  async postModelsEnvironments(params: {
    model_id: string;
    body: CreateEnvironmentRequest;
  }): Promise<Environment> {
    return this._doJson<Environment>({
      method: "POST",
      pathFmt: "/v1/models/{}/environments",
      pathArgs: [params.model_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Activates a deployment associated with an environment */
  async postModelsEnvironmentsActivate(params: {
    model_id: string;
    env_name: string;
  }): Promise<ActivateResponse> {
    return this._doJson<ActivateResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/environments/{}/activate",
      pathArgs: [params.model_id, params.env_name],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Cancels a promotion to an environment */
  async postModelsEnvironmentsCancelPromotion(params: {
    model_id: string;
    env_name: string;
  }): Promise<CancelPromotionResponse> {
    return this._doJson<CancelPromotionResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/environments/{}/cancel_promotion",
      pathArgs: [params.model_id, params.env_name],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Deactivates a deployment associated with an environment */
  async postModelsEnvironmentsDeactivate(params: {
    model_id: string;
    env_name: string;
  }): Promise<DeactivateResponse> {
    return this._doJson<DeactivateResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/environments/{}/deactivate",
      pathArgs: [params.model_id, params.env_name],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Force cancels a rolling promotion */
  async postModelsEnvironmentsForceCancelPromotion(params: {
    model_id: string;
    env_name: string;
  }): Promise<SignalPromotionResponse> {
    return this._doJson<SignalPromotionResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/environments/{}/force_cancel_promotion",
      pathArgs: [params.model_id, params.env_name],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Force rolls forward a rolling promotion */
  async postModelsEnvironmentsForceRollForwardPromotion(params: {
    model_id: string;
    env_name: string;
  }): Promise<SignalPromotionResponse> {
    return this._doJson<SignalPromotionResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/environments/{}/force_roll_forward_promotion",
      pathArgs: [params.model_id, params.env_name],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Pauses a rolling promotion */
  async postModelsEnvironmentsPausePromotion(params: {
    model_id: string;
    env_name: string;
  }): Promise<SignalPromotionResponse> {
    return this._doJson<SignalPromotionResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/environments/{}/pause_promotion",
      pathArgs: [params.model_id, params.env_name],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Promotes a deployment to an environment */
  async postModelsEnvironmentsPromote(params: {
    model_id: string;
    env_name: string;
    body: PromoteToEnvironmentRequest;
  }): Promise<Deployment> {
    return this._doJson<Deployment>({
      method: "POST",
      pathFmt: "/v1/models/{}/environments/{}/promote",
      pathArgs: [params.model_id, params.env_name],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Resumes a paused rolling promotion */
  async postModelsEnvironmentsResumePromotion(params: {
    model_id: string;
    env_name: string;
  }): Promise<SignalPromotionResponse> {
    return this._doJson<SignalPromotionResponse>({
      method: "POST",
      pathFmt: "/v1/models/{}/environments/{}/resume_promotion",
      pathArgs: [params.model_id, params.env_name],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Upserts a secret */
  async postSecrets(params: { body: UpsertSecretRequest }): Promise<Secret> {
    return this._doJson<Secret>({
      method: "POST",
      pathFmt: "/v1/secrets",
      pathArgs: [],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Creates a team API key */
  async postTeamsApiKeys(params: { team_id: string; body: CreateApiKeyRequest }): Promise<ApiKey> {
    return this._doJson<ApiKey>({
      method: "POST",
      pathFmt: "/v1/teams/{}/api_keys",
      pathArgs: [params.team_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Upserts a secret in a team */
  async postTeamsSecrets(params: { team_id: string; body: UpsertSecretRequest }): Promise<Secret> {
    return this._doJson<Secret>({
      method: "POST",
      pathFmt: "/v1/teams/{}/secrets",
      pathArgs: [params.team_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Upsert a training project in a specific team. */
  async postTeamsTrainingProjects(params: {
    team_id: string;
    body: UpsertTrainingProjectRequest;
  }): Promise<UpsertTrainingProjectResponse> {
    return this._doJson<UpsertTrainingProjectResponse>({
      method: "POST",
      pathFmt: "/v1/teams/{}/training_projects",
      pathArgs: [params.team_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Search training jobs. */
  async postTrainingJobsSearch(params: {
    body: SearchTrainingJobsRequest;
  }): Promise<SearchTrainingJobsResponse> {
    return this._doJson<SearchTrainingJobsResponse>({
      method: "POST",
      pathFmt: "/v1/training_jobs/search",
      pathArgs: [],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Upsert a training project. */
  async postTrainingProjects(params: {
    body: UpsertTrainingProjectRequest;
  }): Promise<UpsertTrainingProjectResponse> {
    return this._doJson<UpsertTrainingProjectResponse>({
      method: "POST",
      pathFmt: "/v1/training_projects",
      pathArgs: [],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Create a training job. */
  async postTrainingProjectsJobs(params: {
    training_project_id: string;
    body: CreateTrainingJobRequest;
  }): Promise<CreateTrainingJobResponse> {
    return this._doJson<CreateTrainingJobResponse>({
      method: "POST",
      pathFmt: "/v1/training_projects/{}/jobs",
      pathArgs: [params.training_project_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get the logs for a training job. */
  async postTrainingProjectsJobsLogs(params: {
    training_project_id: string;
    training_job_id: string;
    body: GetTrainingJobLogsRequest;
  }): Promise<GetLogsResponse> {
    return this._doJson<GetLogsResponse>({
      method: "POST",
      pathFmt: "/v1/training_projects/{}/jobs/{}/logs",
      pathArgs: [params.training_project_id, params.training_job_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Get the metrics for a training job. */
  async postTrainingProjectsJobsMetrics(params: {
    training_project_id: string;
    training_job_id: string;
    body: GetTrainingJobMetricsRequest;
  }): Promise<GetTrainingJobMetricsResponse> {
    return this._doJson<GetTrainingJobMetricsResponse>({
      method: "POST",
      pathFmt: "/v1/training_projects/{}/jobs/{}/metrics",
      pathArgs: [params.training_project_id, params.training_job_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Recreate a training job */
  async postTrainingProjectsJobsRecreate(params: {
    training_project_id: string;
    training_job_id: string;
  }): Promise<RecreateTrainingJobResponse> {
    return this._doJson<RecreateTrainingJobResponse>({
      method: "POST",
      pathFmt: "/v1/training_projects/{}/jobs/{}/recreate",
      pathArgs: [params.training_project_id, params.training_job_id],
      body: null,
      successCode: 200,
      errorCodes: null,
    });
  }

  /** Stop a training job. */
  async postTrainingProjectsJobsStop(params: {
    training_project_id: string;
    training_job_id: string;
    body: StopTrainingJobRequest;
  }): Promise<StopTrainingJobResponse> {
    return this._doJson<StopTrainingJobResponse>({
      method: "POST",
      pathFmt: "/v1/training_projects/{}/jobs/{}/stop",
      pathArgs: [params.training_project_id, params.training_job_id],
      body: params.body,
      successCode: 200,
      errorCodes: null,
    });
  }

  private async _do(request: ApiRequest): Promise<Response> {
    const path = request.pathFmt.replace(
      /\{\}/g,
      (() => {
        let i = 0;
        return () => encodeURIComponent(request.pathArgs[i++]);
      })(),
    );
    const init: RequestInit = {
      method: request.method,
      headers: { ...this.headers },
    };
    if (request.body !== null) {
      (init.headers as Record<string, string>)["Content-Type"] = "application/json";
      init.body = JSON.stringify(request.body);
    }
    const response = await this.fetchImpl(`${this.baseUrl}${path}`, init);
    if (response.status !== request.successCode) {
      throw new ResponseError(response.status, await response.text());
    }
    return response;
  }

  // TODO(https://github.com/basetenlabs/baseten-js/issues/2): support non-JSON response content types
  private async _doJson<T>(request: ApiRequest): Promise<T> {
    const response = await this._do(request);
    const contentType = response.headers.get("content-type") || "";
    if (!contentType.includes("application/json")) {
      throw new ResponseError(
        response.status,
        `non-JSON response content type not currently supported, got ${contentType}`,
      );
    }
    return (await response.json()) as T;
  }
}
